### ISSUE TITLE
Use local node for generating subgraph services and rest

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10083]
We have a few places where we use hosted subgraph for generating services and some tests. 

We should replace these with local node in our CI.

**Comment by searchableguy** [comment]
Can we add local subgraph node in regular CI build as well? 
@clemsos

**Comment by clemsos** [comment]
we have one already for integration tests so I guess we could re-use it somehow. The main thing for subgraph is that we have to 

0) start a eth node
1) deploy Unlock contracts
2) parse subgraph config files using the unlock addresses of the contracts we just deployed
3) deploy the subgraph

so that requires some extra steps that are currently in the `docker-compose.integration.yml` and `docker/development` folder

**Comment by julien51** [comment]
https://github.com/unlock-protocol/unlock/pull/10521
