### ISSUE TITLE
AddressInput UI component

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10398]
There are multiple places in our web applications where we use input fields for people to enter addresses. We should create a single component for this that we can re-use everywhere. This component should be added to our `UI` library (along with appropriate storybook stories)
This component should do the following:
* Format validation
* ENS resolution (optional, defaults to true), but keep ENS "visible" (however the value used in forms should be the `0x...` address

It should work natively with `useForm` that we use in many places.

Examples of places where it needs to be used:
* `Referrer` setting on the Checkout Builder,
* `Recipient` or `Key Manager` on the Airdrop Keys form,
* Verifier or Lock Managers in the `Roles` settings.

**Comment by SouravInsights** [comment]
hey, @julien51 i'm interested in working on this issue!

**Comment by julien51** [comment]
Alright! I am assigning it to you and we'll add a 300 USDC bounty paid on Polygon!
Please make sure you copy @searchableguy and @kalidiagne  on the PR for reviews!

**Comment by SouravInsights** [comment]
Hey, @julien51 👋 

Sorry for taking such a long time but here's a draft **[PR](https://github.com/unlock-protocol/unlock/pull/10644)**. But I still need to make some improvements on this so thought of opening up a draft PR first so everybody can see the progress & provide any feedback.

Tagging @searchableguy and @kalidiagne so that you can have a look! 

I'll be out on a vacation for some days but will get back to this as soon as possible.

**Comment by julien51** [comment]
Hey @SouravInsights any chance we can close the loop on this one please? We'd love to use it in https://github.com/unlock-protocol/unlock/pull/10937 for example!

**Comment by SouravInsights** [comment]
> Hey @SouravInsights any chance we can close the loop on this one please? We'd love to use it in #10937 for example!

Hey, Julian. I'm waiting for final approval from @kalidiagne & @searchableguy

**Comment by julien51** [comment]
Thanks for your work on this @SouravInsights !
