### ISSUE TITLE
Gasless claims need to be enabled when a minuscule amount of 1 native token is in a wallet

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#10497]
**Is your feature request related to a problem? Please describe.**
When a wallet has a minuscule amount of a network's native token, which is not enough to cover gas, the user cannot claim a membership without obtaining more native token.

Impacted Polygon wallet: 0x714362Fa571f1AF2CeA8289ee3f6CaB052b5Fb3A

**Describe the solution you'd like**
Checkout should allow for gasless claims when a wallet has less than X native tokens to cover gas. 

**Describe alternatives you've considered**
Checkout should allow users to swap tokens to purchase.
![Screen Shot 2022-12-02 at 10 35 34 AM](https://user-images.githubusercontent.com/32484647/205376538-4e80327b-f86a-41d9-bc7e-1c55ab81bcb9.png)

**Comment by julien51** [comment]
Can do. My concern is that this will get abused. The goal of subsidizing gas is to help people who have never purchased crypto (because they can't or because it's too much work). If you already have some in your wallet, then you probably know how to do it.
It also then becomes _really_ easy to abuse this system... but let's give it a try.

**Comment by julien51** [comment]
Let's actually not do that for now. If users have some amount of token, even very small, they should be able to get more.
