### ISSUE TITLE
CI/tests should not require external services

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10520]
We seem to use a few external services in our tests which is an antipattern as this means our flow depends on things we can change/break arbitrarily, making our job harder!
We should remove these and only use "local" services.

**Comment by julien51** [comment]
A first step would probably be to try to run CI in an environment that does not allow of external calls and see what breaks! Not sure if Github supports that!

**Comment by searchableguy** [comment]
> A first step would probably be to try to run CI in an environment that does not allow of external calls and see what breaks! Not sure if Github supports that!

This can be done inside the docker container after installation using a flag if required otherwise it wouldn't work at the action level as that would break everything. 

To my knowledge, we depend on the following externally 

1. Subgraph
Locksmith endpoints and frontend use subgraph to load data and run tests on it. We don't use local subgraph node here. 

2. Locksmith
There are endpoints which query chain directly on testnets and such. Some endpoints also stitch data from subgraph.

**Comment by julien51** [comment]
I believe this is now fixed? Can you confirm @searchableguy please?
