### ISSUE TITLE
New setting: Email confirmation details

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#10613]
We need to add another lock setting section "Emails" where lock manager can save an extra section (markdown supported) to be included in the confirmation emails sent to users.

**Comment by julien51** [comment]
This section will initially include a single email to be customized (Confirmation) but should enable adding more email types in the future.

**Comment by kalidiagne** [comment]
I this still required? 

We can integrate as we do for `keyMined` and `keyAirdropped` custom content. 

Also, another point, we have a custom email like
- `keyMined-0x5f1c54dEDE0d96F49EEd8F57f653b24d41f4BDd6` 
- `keyMined-0xc4bcBaa594843881Fc3957C9104965D0f7cFb1FF`

I suggest adding a way to specify if we want to include custom content or replace all so that we can get rid of this custom replacer in the codebase.

**Comment by julien51** [comment]
This is done! We can close.
