### ISSUE TITLE
Automatically switching network when required

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10631]
We have too many places where we need to ask user to switch network to make a transaction. Unfortunately this results in lot of repeated code and we don't have a good pattern to handle this.

We should think about how we can make this easier both on our frontend as well as unlock js.

**Comment by julien51** [comment]
Once we have a good solution for this, then we can probably use the same approach to require users to connect their wallet if it's not connected and just use the "token" (SIWE message signed) to identity whether they are connected. This will solve https://github.com/unlock-protocol/unlock/issues/9197 because for Unlock accounts, we _never_ need to "connect wallet" as all transactions are sent thru an authenticated API call.
