### ISSUE TITLE
Set Referral fee setting does not include an address input

### ISSUE THREAD

**Issue by searchableguy** [unlock-protocol/unlock#10649]
**Describe the bug**
Referral fee setting should include an input to include the referrer address when setting up the referrer.

**Comment by julien51** [comment]
Yes, it is because we currently don't have av event when adding new referrer fee, which means we don't have a subgraph to easily list referrer fees... and that means we can't really show in the UI addresses with a referrer fee which is why we decided with @kalidiagne to only set the "global" referrer fee... until we can get unblocked.

**Comment by julien51** [comment]
Assigning to @clemsos so he can add the event to the PublicLock contract.
After that we will be able to update the subgraph, and show the list of referrer + fees on the UI and finally let lock managers set referrers.
