### ISSUE TITLE
Support all the chains!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#11116]
We need to change how we support all the chains on the UI.

When deploying a lock, we should only show a limited number of options: Ethereum, gnosis, polygon, optimism, arbutrum and goerli.
We should also show a message indicating that other networks are supported and that the user should select that network in their wallet if they want to deploy on today specific network (we then show a message if the network is not supported).

The rest of the application is unchanged.

**Comment by searchableguy** [comment]
I would limit the options using a field in the config file so it's changeable everywhere.

For the supported network, I suggest we have a button at the top navigation bar to see all supported networks at once for ease of discovery.

This pattern is used by guild.xyz and it works well since we can also add button to allow adding a chain from there since many users don't have it in default metamask.

**Comment by julien51** [comment]
Indeed, I think the Guild approach is a good approach for the dashboard! I will work on this shortly.

**Comment by julien51** [comment]
One thing I wonder is whether we should load all the subgraphs on the locks and keys pages. I worry this will take longer and longer... Maybe we can load a good set of defaults (the ones above) and then have a setting where someone can save extra ones to be loaded.
