### ISSUE TITLE
Versionning the Lock Smart Contract

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#1116]
Earlier in the week we added the ability for the lock owner to list the keys sold on their lock.
The initial approach was to retrieve each owner one by one and then pull the corresponding key one by one. This was fairly low performance but "worked".

@akeem implemented a function on the publicLock to make that faster via pagination https://github.com/unlock-protocol/unlock/pull/1018 (in the form of getting X owners at once and then getting all of their keys). Not 100x better but still, an improvement.

Later, he introduced a new function inside the web3Service which used that new smart contract function. https://github.com/unlock-protocol/unlock/pull/1062

Unfortunately, all of the previously deployed locks on Rinkeby do not support this new smart contract method, which means that listing keys do not work for them anymore.

As a way to move forward, I suggest the following:

* Update our rinkeby deployed contracts so that any new lock will now support the new API. This means that our mainnet version also supports this new API.
* All of the previously deployed lock will keep failing on rinkeby (but I guess that is why we have rinkeby). 
* We should implement version numbers in the Locks which are updated when adding new features so that the web app (or other clients) may know what kind of features are available to them.
* We should either find a way to upgrade a lock, or (probably easier), to migrate them (deploy a new version of them with the data "copied" from the old lock to the new lock.

**Comment by akeem** [comment]
I think the following would provide us with the most robust solution, but I guess we do need to ensure that we have a consistent reference to the deployed locks.
>We should either find a way to upgrade a lock, or (probably easier), to migrate them (deploy a new version of them with the data "copied" from the old lock to the new lock.

Can we burn the current locks deployed on rinkeby? If not I think we can conditionalize the front end to fall back to the iterative approach of listing keyholders

**Comment by julien51** [comment]
@akeem We cannot burn existing contracts at this point (but we should add that too!).

And yes I think we can conditionalize to fall back, using version numbers for example.

**Comment by julien51** [comment]
The other part of versioning is probably that we should keep the "old" ABIs around...

**Comment by nfurfaro** [comment]
This is something that appeared on my radar yesterday as well in another form. Some of the changes by @hardlydifficult which bring us closer to erc721-readiness have added new storage fields to our PublicLock contract. I'm pretty sure zos will refuse to upgrade on rinkeby until we move them to the end of the storage field declarations (basically we're only allowed to append new storage). Which is probably enough to satisfy zos. 
It did bring versioning our contracts to mind though, and the method we choose to do so. 
- Zos'json has a "version" field and a "bump" command for the cli, not sure if we want to use it or not.
- WHile we're getting ready to deploy v0 on mainnet, it will actually be the second upgrade on rinkeby. I propose that we start our version numbering with our mainnet deployment being Unlock (implicit V0), and then increment after that.
- For the smart contracts, we can choose to add new functionality it 3? ways.
  1.) modify `Unlock.sol` directly and change the name. I don't like this one.
  2.) Copy-paste the current version of Unlock into a new file, `UnlockV1.sol` and modify as necessary.
  3.) Inheritance. Create a new file, `UnlockV1.sol` which inherits `Unlock.sol` (V0). I prefer this method, as `UnlockV1` would contain only the changes (easy to review), and all new storage is automatically appended to that of `Unlock.sol` V0.

As far as upgrading (migrating) Locks, I agree it's something we'll have to do. I started a doc a while back which had part of this process brainstormed:
https://docs.google.com/document/d/1ffepd7rawqTXDwvyS5DuHcsxZVQGoU9hj79i6aDIoUw/edit#heading=h.cm01588mxh7k
One thing we'll definitely need to add is the ability to “set” the `address unlockProtocol` field on the PublicLock.sol contract, in order to point to the new Unlock contract.

As far as migrating, it would be great if we knew when the last lock had migrated so we know when we could "burn" the old contract. Pretty sure that "burning" (self-destruct) still allows for ether to be sent to the contract, and never again retrieved... cc @hardlydifficult ?

**Comment by nfurfaro** [comment]
Also to consider here is the cost of "migrating" every lock each time we upgrade, which is linked to how we're using the upgrade process.
- If we only upgrade rarely when absolutely necessary, the cost to migrate may not be too bad.
- If we're treating upgrades more like a conventional dev process "moving fast, breaking things, continuous delivery" etc..., migrating could become very expensive.

One alternative is to make our locks upgradeable as well, but we'ed need to look carefully at how this would be done. My hunch is that allowing for the migration of data, and only upgrading when really necessary, is probably going to make the most sense...

**Comment by julien51** [comment]
> I'm pretty sure zos will refuse to upgrade on rinkeby until we move them to the end of the storage field declarations (basically we're only allowed to append new storage). Which is probably enough to satisfy zos.

That is scary and there is one thing that I do not fully understand about the memory structure. 
The deployed Lock should not be in the memory space of the Unlock smart contract right? They are indepedend smart contracts which have been deployed by Unlock but not like variables *inside* Unlock.sol?

I guess the one thing that is *inside* the Unlock smart contract code is actually the ABI for the PublicLock smart contract?

**Comment by julien51** [comment]
Regarding migrating (let's reserve the term upgrading for Unlock only to avoid confusion), this is a feature we can do *after* versioning. This seems fairly straigtforward:
1. Deploy a brand new PublicLock (with a new version), assign all of the keys for the old one to the new one.
2. Ask the owner to update the snippet of code.

We just discussed this with @akeem and this is where using ENS would be helpful. We put the ENS sub-domain in the snippet and then the migration process takes care of changing the assigned value.

**Comment by nfurfaro** [comment]
> The other part of versioning is probably that we should keep the "old" ABIs around...

@julien51 could you elaborate on your thoughts here? 
I'm thinking that we should keep the "old" versions of our contracts in the codebase for reference, and of course, we can always compile them to get the ABI/bytecode. I would like a way to prevent modifying these old versions...maybe adding them to `.gitignore` as soon as we release a new version?

**Comment by nfurfaro** [comment]
To summarize where we're at with this:

1.) The lock contract now has version numbers implemented, but none of the new versions have been deployed yet as this requires an upgrade of `Unlock.sol` via zos.
2.) `Unlock.sol` has been modified to set the lock version number on creation, but hasn't been upgraded.

It probably makes sense to continue to modify the new version of `PublicLock.sol` (V1) up until we're ready to Upgrade Unlock and launch `UnlockV1.sol`, at which point the new PublicLock version will go live (`UnlockV1.sol` will create and deploy V1 of `PublicLock.sol`)

**Comment by nfurfaro** [comment]
Closing as this is done.
