### ISSUE TITLE
Redirect URL accessible before checkout though the "X" at the top right

### ISSUE THREAD

**Issue by 0xNFTBUZZ** [unlock-protocol/unlock#11556]
it is important that the redirect url is only accessible after checkout and having that secret link access via the "x" at the top of the screen makes it not necessary to unlock. 

Please have the "x" at the top right  return the user back to separate URL than the redirect url

**Comment by 0xNFTBUZZ** [comment]
the redirect url is labeled as "The address of a webpage where the user will be redirected when they complete the checkout flow." but as you can see [HERE](https://app.unlock-protocol.com/checkout?id=b397f47c-7695-4bb2-aa07-c45adb652402) even before the checkout is completed, the redirect link is accessible by clicking the X at the top right of the page. 

I am currenlty using gumroad to sell digital products and redirecting members after checkout is key in my website flow.
[my website](https://launch.themes.fyi/#pricing)

**Comment by julien51** [comment]
@0xNFTBUZZ I am sorry for the delay here. 

The "checkout URL" is just a flow to checkout, it does not do token gating itself. The redirect URL should just be interpreted as " the user will go to this page once they're done with the checkout flow, whether they have purchased or not".

There is *no way* the checkout URL can "enforce" token gating on a 3rd party site. Of course, we could have 2 different URLs but it would not solve your issue because once the "success URL" is known, someone could easily share it with someone else who would then get access _without_ actually owning one of your NFTs. Additionally, someone could just read the configuration of your checkout URL to find what the "success URL" and go there without actually buying a membership NFT.

> I am currently using Gumroad to sell digital products and redirecting members after checkout is key in my website flow.

The difference here is that Gumroad does *more* than just the checkout part. They also have "host" the content and they can easily verify that indeed someone has paid them to access your content.

If you want something like that, you will need to use something like the [Unlock Wordpress plugin](https://github.com/unlock-protocol/unlock-wordpress-plugin) and host your content on a WordPress site for example.

**Comment by julien51** [comment]
@0xNFTBUZZ Does my explanation make sense?

**Comment by julien51** [comment]
Closing as stale
