### ISSUE TITLE
Add Avalanche as an available networks in Events and Certification by Unlock Labs

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12657]
**Is your feature request related to a problem? Please describe.**
Avalanche is not an available network in Unlock Labs Events and Certification apps. Ava Labs is interested in using both apps. 

**Describe the solution you'd like**
Add Avalanche as an available network in Events and Certification by Unlock Labs.

**Comment by julien51** [comment]
@patrickworkman We already support avalanche completely. However it is not a *featured* networks. 

Since we support 11 networks right now, and for user simplicity, we don't show them all, but show a subset of *featured* networks. Avalanche is _not_ one of them, but if you connect your wallet to Avalanche first you will see it in the list of options!
