### ISSUE TITLE
Token holder link can go to wrong URL in Dashboard

### ISSUE THREAD

**Issue by ccarfi** [unlock-protocol/unlock#12785]
<img width="1596" alt="Screen Shot 2023-10-05 at 5 15 25 PM" src="https://github.com/unlock-protocol/unlock/assets/214760/89358593-e2e4-4b38-87f1-f5df53cbd6fe">

It appears this UI element may be hardcoded to always go to `blockscan` even when on other networks such as Polygon. Clicking on this element throws a 404 in this instance where the lock is on Polygon, and the token holder address does not exist on mainnet.

**Comment by julien51** [comment]
Hey @ccarfi this is actually intentional. Blockscan is a "generic" way to show all networks for a given address.

I tried reproducing the 404 issue you're seeing but I do not have that: https://blockscan.com/address/0xb1f32d7bbd638a91eaa2e7c28ac838361529e13f

<img width="1214" alt="Screenshot 2023-10-11 at 10 13 19 AM" src="https://github.com/unlock-protocol/unlock/assets/17735/3241bbeb-322c-4a7d-b7b4-aef67a80b989">

Would you be able to provide more details regarding the 404 part of the issue?
