### ISSUE TITLE
Events: Add CTA to an organizer's EDP on the Membership Dashboard they are directed to through their EDP

### ISSUE THREAD

**Issue by patrickworkman** [unlock-protocol/unlock#12870]
**Is your feature request related to a problem? Please describe.**
When organizers are directed to the Membership Dashboard from the EDP they have created, there needs to be a CTA to return to the EDP. Organizers need an easy way to go back to their EDP so they can share and promote their event. 

**Describe the solution you'd like**
Add an 'Event Details Page' CTA to the Dashboard.

**Describe alternatives you've considered**

- When organizers click the Manage Attendees CTA from their event detail page, open the Membership Dashboard in a new tab.
- Add a 'Share Event URL' under the contract name on the left panel of the Membership Dashboard, directing organizers to the EDP they've created.

**Comment by julien51** [comment]
We don't want organizers to have to go to the dashboard because it would be confusing to them.
For now, we have a link to all their events on https://app.unlock-protocol.com/event which is not ideal.

We should make a better use of https://app.unlock-protocol.com/ for that purpose.
I will think of the best way to handle that.
