### ISSUE TITLE
Lock Deletion

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#1348]
**Is your feature request related to a problem? Please describe.**
Goal (in priority order):
 - Enable a migration path, allowing Lock owners to upgrade and benefit from new features
 - Protect users from losing money on invalid Locks
   - Impacts purchase and maybe transfer (protecting users on the secondary market)
 - Be good ETH citizens and minimize bloat if we can

**Describe the solution you'd like**

 - Proxy purchases through Unlock & Self Destruct: this allows us to achieve all goals

This means that all purchasing would be a transaction to the Unlock contract. It of course would reference the specific Lock of interest, likely by address but we could find another ID.  The Unlock contract would then forward the request to the correct Lock and require positive confirmation (i.e. it returns true).  This way once the Lock self destructs it’s not possible for users to lose money purchasing an invalid Lock.

This approach add security/confidence for users of the Unlock system.  By requiring purchasing to go through the main Unlock contract first, we can guarantee that we created the Lock.  This may be important as without this malicious users could create a contract that’s similar to our Lock and it may be compatible with our JS, but includes some unexpected and potentially dangerous logic.

**Describe alternatives you've considered**
 - Self Destruct the Lock: this risks users funds.  If someone attempts to purchase a key, the ETH will be burned and the user gets nothing.
 - isAlive: this allows to achieve goal 1&2 but not 3

**Additional context**

**Comment by julien51** [comment]
I think this is fine... but does it actually prevent people from calling purchase directly on the lock? (I guess we can use a modifier to ensure that the purchase function is coming from Unlock?).

This would actually probably completely change how `purchaseFor` and co work on the locks, right? There is no need for them to callback to `Unlock` anymore?

**Comment by julien51** [comment]
I also wonder about the implications in terms of messaging because it means that in practice, people purchasing a key are actually sending the Eth (or other) to an Unlock owned smart contract? Could this mean that we become a middleman?

[I know that in practice the fact that the lock calls back to Unlock is probably very similar...]

**Comment by hardlydifficult** [comment]
Yes, this prevents people from calling purchase directly on the Lock.  No functionality is lost though as they can make the call via a function in Unlock.

In terms of being a middleman, I believe this changes nothing.  Yes the money goes to Unlock and then the Lock, however it is impossible for Unlock to be stuck holding any ETH in the process.  This process simply allows us to guarantee that 1) the Lock was created by us and therefore inherits certain expectations and 2) the Lock is still valid.

Oh I should add a consideration: do old Keys continue to work?  If we allow selfdestruct, they are worthless immediately.  Using `isAlive` (w/ or w/o the proxy through Unlock) allows us to block purchases and transfers while allowing old Keys to continue to grant access to content.

The best option for users overall may be using `isAlive` and proxy through Unlock.  This protects users funds, protects against fake Locks, and allows old Keys to continue to function while a Lock owner migrates to a new version.

**Comment by julien51** [comment]
So I thought a lot about this and I think we should not do that. We cannot be a middlemen. Since the Unlock contract is upgradable (by us!) it means that in theory yes we could decide to change the rules and intercept payments and/or take a fee.

This all boils down to the fact that the `purchaseFor` methods are payable while the "callbacks" from the lock to Unlock are not.

I firmly believe that we should not do that change, even though, indeed that would be a strike on the 3 requirements.

Coming back to the list of priorities, which I agree with, I wonder if the solution to each is different. For example:

    1. Enable a migration path, allowing Lock owners to upgrade and benefit from new features

This can probably be done in a completely "disconnected' way. We should probably have a `grantKeys` function which only the lock owner can invoke which would assign keys to addresses (with an optional data and expiration for each). This lets let lock owner easily create a new lock, "copy" batches of keys and change the pointers on their site to the new lock. This would arguably be gas-expansive for large locks, but I think that is "fair" if they want to use a newer lock (or they could wait for all keys to expire too...)

    2. Protect users from losing money on invalid Locks impacts purchase and maybe transfer (protecting users on the secondary market)

My understanding is that this one is indeed slightly more complex without some kind of "proxy" which could return the Eth when the lock does not exist anymore. BUT, I also honestly think that in the future the Eth-based lock will probably be more of an exception than the rule. The ERC20 locks will probably be more popular and IIRC the problem would likely not happen for them. 
A workaround that I am considering for the Eth-based locks would actually to turn them into Wrapped-Eth lock and I _think_ we could do the transaction of Eth -> WETH -> Lock * in a single transaction. This would be more expensive in gas but also safer for several things.

    3. Be good ETH citizens and minimize bloat if we can

I actually think this is very important. I think this can be achieved in 2 steps: mark the lock as "deprecated" and prevent any key purchase and, once all keys have expired, wipe it out.
This adds a flag and a check on all purchases but this should still be fairly low, gas wise?

What do you think?



*: this is actually a mechanism that I'd love to see work for any ERC20 Lock: the lock is using an ERC20 and the user has another one but we could in a single transaction (using 0x?) allow the user to pay using their own currency to purchase a key.

**Comment by hardlydifficult** [comment]
1) agree.  We should probably track that as a separate issue/feature.  

We need to keep in mind the cancelAndRefund feature here as well. If the Lock owner simply re-creates Keys on the new Lock without first invalidating them on the old lock (or first deprecating the old lock which could also block cancel attempts) then a user could try to cancel both the new and the old and potentially profit.

An alternative is instead of manually transferring keys, we could build the ability for future Locks to acknowledge keys from a prior version.  Saves on gas and avoids a manual migration process.  (note: even if we went with this approach, I still think giving the Lock owner the ability to give away Keys is a nice feature).

2) while I believe that's technically possible, I'm not sure if anyone offers this service yet.  I just checked the latest wETH contract and it does not have anything to support that out of the box.   I poked around 0x and don't see an option for this either, but I may be missing it.  

I believe it requires some contract to accept ETH and call information, deposit the ETH into wETH, pass forward any call information (contract, method, parameters) and then require some positive confirmation (e.g. return true -- this is only necessary if we want to allow for Locks to selfdestruct).  Now we could build that contract, but it touches the middle man concern again - the difference is we could choose to make this not-upgradable.

3) Yes 2 steps makes sense.  Use an `isAlive` type approach to stop new purchases for a period of time before calling the selfdestruct.  The concern is we can not know if all keys have expired - once a Lock has more than a handful of keys, we won't be able to walk the array before running out of gas.

We could however add a cooldown requirement.  e.g. if you want to destroy a Lock, first deprecate it and then you can call selfdestruct after expirationDuration has passed.  This would ensure almost all keys are invalid by the time selfdestruct is called, the only potential losers are those who topped off their key on a secondary market to the point that their duration remaining is greater than the original expirationDuration.

This raises an incentive concern.  Why would the Lock owner take the time or spend the gas on calling selfdestruct after the cooldown has passed?  
 - Maybe we could add the ability for the Unlock owner to call selfdustruct after the cooldown... however if in that rare case a user does lose a valid key, that would be on us.  That said, this is a manual process and our team could walk the entire list of keys to ensure none are valid before making the selfdestruct contract call.
 - Or maybe the Lock owner cannot withdrawal all funds until the selfdestruct.  This would help in ensuring funds remain in the contract allowing people to cancel their key and get a partial refund.

**Comment by nfurfaro** [comment]
Just weighing in on these three points.
1.) I like the idea of a `grantKeys` function, but also would like to avoid the need to migrate keys if possible. I think the idea of allowing locks to accept keys from a prior version (or indeed, from another lock entirely to allow for "packages deals - buy a key to my site and gain access to these others as well...) and think we should seriously consider this. I do think the 2 ideas could work together, it doesn't have to be one or the other.

2.) I'm not sure about the viability of the wETH approach, but if we have a modifier `isAlive` that we use on all payable functions we should be ok for the locks that accept eth as payment. That is, `isAlive` will not evaluate to `true`

3.) Fully on board with a 2-step approach. I'd love it if we could avoid the need for Unlock to manually check old locks for valid keys and call `selfdestruct`, but  (in addition to concerns above about not being able to walk the entire array without running out of gas) I don't know that we could count on lock owners to delete their own locks. Taking this on may be something Unlock has to take on as part of being good citizens.

**Comment by hardlydifficult** [comment]
@nfurfaro I think we can close this and simply track #1450 going forward.  Do you agree?

**Comment by nfurfaro** [comment]
Agreed.
