### ISSUE TITLE
Integration tests does not run against latest versions of the contracts 

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#13498]
The integration tests deployment tasks in `docker/development/eth-node` pulls the Unlock hardhat plugin directly from npm which does not contain development versions. This was done to avoid including the test node as a workspace in the monorepo but that means integration tests arent running against dev versions.

An approach will be to copy the `hardhat-plugin` and `contracts` dist folder and add them as workspaces for the hardhat node build

**Comment by julien51** [comment]
Hum, I am not sure this is a bad thing though. The goal of integration tests is to make sure that everything works "as expected" for users "now". Since the dev contracts are not released yet, I am not sure it is bad that we test outside of them.
That said, when we're about to release the new contracts (and then before we actually trigger the upgrades) that is when the integration tests should start testing the new release.

So IMO, these tests should run against the contract's package "latest" versions. wdyt?
