### ISSUE TITLE
web3Middleware should not try to retrieve when no the redux store does not have an account

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1362]
**Describe the bug**
When loading the paywall with no account, it fails with an exception in `web3Middleware`

The lines in question are:

```js
      if (action.type === ADD_LOCK || action.type == UPDATE_LOCK) {
        const lock = getState().locks[action.address]
        web3Service.getKeyByLockForOwner(
          lock.address,
          getState().account.address
        )
```

When pausing on the `getKeyByLockForOwner` when logged in, the lock has an address. When pausing while logged out, the lock has no address, and does not exist in state, so `lock` is undefined. In addition, a casual look shows that we are assuming that the `account` in state has an address, where it is in fact `null` when there is no account.

**To Reproduce**
1. run `UNLOCK_ENV=staging npm run dev`
2. go to `http://localhost:3000/paywall/0x42dbdc4CdBda8dc99c82D66d97B264386E41c0E9`
3. See error

**Expected behavior**
lock displays under a "missing wallet" error

**Screenshots**
<img width="1360" alt="screen shot 2019-02-01 at 9 28 23 pm" src="https://user-images.githubusercontent.com/98250/52158641-5241a980-2668-11e9-9018-cad483e9af73.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome with Metamask logged out

**Comment by julien51** [comment]
The distinction between the the `walletService` and the `web3Service` is really between read and write.
The `walletService` requires the use of a wallet to sign transactions, while `web3Service` does not because it only reads content from the chain.

The bug you're seeing is real, but I do not think it is a problem inside `web3Service`. In practice, to retrieve the a key from the lock, we do not need to sign any transaction... we just need to know on on which lock and for which user we're trying to load the key.

I believe the bug probably lies in the `web3Middleware` which invokes the `web3Service` without a valid address.

When there is no logged in user, we should not show a "missing wallet" error in that case. Since this is on the paywall page, we should just show the "default" paywall with a lock that the user can click on...

**Comment by cellog** [comment]
yes, I constantly confuse the two words, thanks for that fix to the title :)
