### ISSUE TITLE
Determine how to store paywall metadata on content

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1442]
Ideas for solutions:
- Using data attributes on script tag
- Using new meta tags

**Comment by cellog** [comment]
Based on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta and on http://ogp.me/

it looks like using `meta` tags is the standard way to communicate information to a parser, which our paywall script is.

The official docs for meta tags recommends using the `name` attribute but opengraph uses the `property` attribute. Because we are not going to be implementing standard HTML meta tags, it is best to use `property`. Examples of `name` usage are setting the charset, or document SEO info like the `author` meta instruction or the `description`.

I propose we use this consistent approach to any metadata:

`<meta property="unlock:<propname>" content="<content>" />`

The paywall.min.js script will parse these values out into an object, and send them using postMessage.

This is preferable to using query parameters for 2 reasons:

1) postMessage has no size limit: https://stackoverflow.com/questions/20532640/what-is-the-maximum-size-for-the-postmessage-method-that-enables-inter-frame-com
2) URL length is limited to 2000 characters total: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

@cnasc @julien51 @benwerd opinions/critiques welcome. Once this is approved, implementation will be simple on the paywall side.

**Comment by julien51** [comment]
I think we should not forget that a given page can have multiple locks (and a key to any of them will unlock the content)...
Now, some of the metadata may be specific to a given lock and some of it may be shared between the locks (specific to the paywall itself).
For example:
* The lock name is obviously specific to a given lock, 
* The number of "dismisses" is on the other end specific to the paywall.
* The sentence which tells the user to purchase a key is also specific to the paywall.

Another important aspect to remember is that we eventually want to be able to lock only parts of a page, rather than the full page, and again with several locks.

**Comment by cellog** [comment]
all good points.

we can easily add a data-lock property for lock-specific attributes

`<meta property="unlock:<property name>" data-lock="0x...." content="..." />`

Alternately, we could extend the property name:

`<meta property="unlock:0x..:<property name>" content="..." />`

I prefer the first approach.

I think this will easily extend for multiple locks, but we should revisit this when the use cases become more concrete. For a large number of locks, it will likely be a better option to define a separate script file that defines a JSON object instead, to save on unnecessary bytes, and to take advantage of browser caching of the file.

**Comment by julien51** [comment]
Let's try to write an example of a `head` section which covers our base use case?
Also, as much as I love the fact that we use `<head>` I think we should consider that it is not always practical/possible to edit the `head` part of an HTML document in some hosted platforms (like Tumblr or SquareSpace irc). I think we need to also consider the use of tags in the `<body>`

**Comment by cellog** [comment]
ok. I'll think about what solution we could use that works in both `<head>` and `<body>` and come up with a `<head>` example based on the `<meta>` tag approach until then

**Comment by cellog** [comment]
```html
<meta property="unlock:paywall-text" content="Subscribe to the Unlock Times" />
<meta property="unlock:paywall-type" content="leaky" />
<meta property="unlock:paywall-type-leaky-num" content="3" />
<meta property="unlock:lock" content="0x...." />
<meta property="unlock:lock-description" data-lock="0x...." content="Monthly" />
```

Here is what a script-based solution might look like:

```js
<script type="text/javascript">
Unlock.setup({
  paywall: {
    text: 'Subscribe to the Unlock Times',
    type: {
      type: 'leaky',
      num: 3
    },
    locks: {
      '0x...': { description: 'Monthly' },
      // ...
    }
  }
})
</script>
```

We would provide a simple object:

```js
window.Unlock = {
  setup(params) {
    // parse the params and pass them to the paywall
  }
}
```

We can also easily compress the script version since it is intended to be machine-readable, and pass the value as-is to postMessage, after validating and sanitizing the input.

The script version would also simplify the paywall script, as we would no longer need to scrape the page for `<meta>` tags, and instead wait for the script to push the paywall information to it.

**Comment by cellog** [comment]
There are a few other considerations.

If we use a script-based version, it introduces some issues with the existing paywall. The question would be do we support the handful of locks that are out there right now and keep the `paywall.min.js` as-is? If so, then we simply need to provide a different paywall script, perhaps `paywall-2.min.js`

The rest of this comment assumes a clean break, and that we use `paywall-2.min.js`. Instead of:

`paywall.min.js` meta-tag based design, extended for metadata
1. iframe creation
2. mutation observer listening for `meta` tag containing the lock address
3. `postMessage` listening
4. `postMessage` sending of metadata

`paywall-2.min.js` script-based design
1. iframe creation
2. listen for script call
3. `postMessage` listening
4. `postMessage` sending of metadata

In both cases, in order to pass the meta-data to the paywall, we will need a round-trip postMessage, something like:

1. iframe loaded
2. iframe sends "OK I'm ready" to the `paywall-2.min.js` script
3. `paywall-2.min.js` sends the meta-data to the iframe.

The challenge is that the script call to pass metadata to `paywall-2.min.js` will probably give the data before the iframe has sent its "OK I'm ready" message. In this case, it will need to be saved and then posted to the iframe when it is ready.

On the paywall app side, the paywall can `useListenForPostMessage` to grab the metadata ost and use it to modify the UI. It will also need to use `usePostMessage` to send the "I'm ready" message.

**Comment by cellog** [comment]
further research shows that simply setting a static `window.unlockPaywallConfig = {...}` is the best way to go. This will be the way it works, and then we can use this config in multiple ways going forward, but initially it will be `postMessage`d to the paywall
