### ISSUE TITLE
Tons of failing PropTypes on the Dashboard

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#1617]
**Describe the bug**
When visiting the dashboard, the console gets a ton of red ink from failed prop types. They all seem to be things that are strings instead of the expected type. 

**Expected behavior**
Prop types should not fail

**Comment by cellog** [comment]
this is because the dashboard is displaying before we have an account. We should display a loading spinner to avoid this.

**Comment by cnasc** [comment]
As decided in our meeting earlier, this is the venue where we'll talk about PropTypes in general.

- What do PropTypes actually do for us?
  - They don't seem to catch issues before they go live
- Are there ways we can use them more effectively?
  - For example, finding out if a change in one place has broken a PropType contract elsewhere
  - Is it possible to trace PropTypes statically, e.g. as part of a pre-push hook?
- It sounds to me like what we really want is more of a proper type system that can integrate with the editor, etc. So maybe in the future PropTypes are obviated if we move to TypeScript even in just parts of the codebase.

Feel free to chime in!

Tags: @julien51 @benwerd @akeem @nfurfaro @hardlydifficult

**Comment by benwerd** [comment]
I'm very pro-propTypes. In a dynamically typed language it's incredibly easy for the wrong value to find its way to a function parameter, creating weird bugs that can be hard to track down. My biggest complaint is actually that they throw console warnings instead of a stronger error, which speaks to your comment about them not catching issues before they're live.

I'd be in favor of using TypeScript in _addition_ to PropTypes, to add type safety across the board. I think that could be particularly useful for transaction parameter types, which seem like they could be easy to accidentally get wrong.

**Comment by cellog** [comment]
There is one change that could make a difference. Basically, we can convert warnings to errors in the tests

```js
const error = console.error
console.error = function (message) {
  error.apply(console, arguments) // keep default behaviour
  throw (message instanceof Error ? message : new Error(message))
}}
const warn = console.warn
console.warn = function (message) {
  warn.apply(console, arguments) // keep default behaviour
  throw (message instanceof Error ? message : new Error(message))
}}
```

Stick that in jest.setup.js and we will see all warnings become test failures, particular in the snapshot tests

This is the key part - if we see a prop-type failure, we should make a story that replicates it when we fix the warning. Then we have a regression for that.

From what I have seen, there are 2 paths. 1 is to use PropTypes + good testing and hope (they are turned off in production), the other is to use typescript + good testing. Types have to be used for props, so it works out great, as it will catch anything before build. However, I don't think there is any chance we have the humanpower to rewrite any of the code in typescript any time soon. My 2 cents.

**Comment by julien51** [comment]
Thanks for sparking the discussion @cnasc !

As we all know propTypes are not "enforced" at this point (and not sure they are enforceable). When we started adding them the goal was to set us on the right path and make sure we caught the most obvious bugs/issues but of course they're not enough.  They are more documentation than code in a way: providing hints rather than altering execution.

> * What do PropTypes actually do for us?
>   * They don't seem to catch issues before they go live

That's right and this was really a way to help us catch the lowest hanging fruits. We do need something more robust like full type checking.

> * Are there ways we can use them more effectively?
>   * For example, finding out if a change in one place has broken a PropType contract elsewhere
>   * Is it possible to trace PropTypes statically, e.g. as part of a pre-push hook?

I am *strongly* against turning them into error, at least for now because we will trigger errors in production which we have not been able to detect in dev/testing. We should however try to report them from production if we can.

* It sounds to me like what we really want is more of a proper type system that can integrate with the editor, etc. So maybe in the future PropTypes are obviated if we move to TypeScript even in just parts of the codebase.

Exactly! I think we need to type-check our apps... and then maybe PropTypes will go away. 

PS: When you talk about the dashboard you talk about the account missing? It is legit: we _should_ have an account to load the dashboard (whose dashboard are we loading if not?), the way to fix this is to "delay" rendering of the dashboard until there is actually an account.

**Comment by cnasc** [comment]
> PS: When you talk about the dashboard you talk about the account missing?

That warning is there, but also when you create a lock on the dashboard, it complains that a number of props are invalid because they are strings rather than the appropriate type. I guess the genesis of that problem is elsewhere, but if the PropTypes were errors in test, that could have been caught earlier. I don't know if that failure really caused any harm, but the fact that it sneaked through is probably a cause for concern.

**Comment by julien51** [comment]
Pointing to https://github.com/unlock-protocol/unlock/issues/1449 as part of this issue ;)

**Comment by cnasc** [comment]
#1802 brings up another fun thing about PropTypes: when they fail, it isn't immediately obvious where the failure occurred. The error message in the storyshots PropType warning provides no useful context, so I have to hunt around to find the spot where it failed.

**Comment by cellog** [comment]
True. I use the title of the failing test in the summary at the bottom of tests to find it, but this is not intuitive

**Comment by cnasc** [comment]
That's part of the issue, the test didn't fail, just provided a warning. And the source was the `storyshots.test.js`. Luckily `ag keyPrice .` found the bad one.

**Comment by cnasc** [comment]
I think that with TypeScript support getting merged in today, we can consider this issue closed.
