### ISSUE TITLE
extract polling from the web3/walletServices

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1652]
In the interest of separation of concerns, and refactoring the web3Service and walletService to allow trimming the new paywall for both speed and ease of feature addition, refactoring to create a separate polling function similar to `setInterval` that uses `setTimeout` internally, and then using it in the `web3/walletMiddleware`s instead of the Services will allow several desirable conditions:

1. testing becomes much simpler. No need to pass in random parameters to the constructor of `walletService`, because it no longer does any calls to setTimeout
2. it becomes possible to turn off polling if it is not necessary. The paywall does not need to poll for account changes when running in coinbase wallet

**Comment by julien51** [comment]
I have already remove the account polling on `walletService` in https://github.com/unlock-protocol/unlock/pull/1627

However, I am opposed to removing the transaction polling from web3Service.
There is a key difference between `walletService` and `web3Service`:

* `walletService` only "reacts" to transactions created by the application. As such it is probably a better pattern to use callbacks for it, rather than an event emitter.

* `web3Service` on the other end handles all kinds of transactions, most of them are not being sent by the applications and changes are triggered by the chain itself (when new blocks are mined). As such, it should be an event emitter which implementers (middleware in the case of redux, or other layers in other cases) listens too. I think it is important to *not* expect the implementer code to perform polling itself, but just *wait* for the content it needs.

I think your question was more applicable to `walletService` which is solved ;) Feel free to close!

**Comment by cellog** [comment]
I am not wanting to remove it, but to extract it from the service so that it can be controllable. There is always a trigger for the polling, which is the first call to getTransaction, which is always a manual trigger.

If the polling is manual, it becomes possible to listen to specific transactions. Currently, the event emitter is the entire service rather than the single transaction because the polling is hidden. In most cases in the unlock-app this is fine because again all state is centrally handled. In the paywall, this is less ideal.

May I do a quick PR so you can see what I am proposing before you reject it out of hand? I'm trying to make the service paywall-builder :)

**Comment by julien51** [comment]
> If the polling is manual, it becomes possible to listen to specific transactions.

I am not sure what you mean here? 

> May I do a quick PR so you can see what I am proposing before you reject it out of hand? I'm trying to make the service paywall-builder :)

If you want to experiment, go ahead but please time box it!

**Comment by cellog** [comment]
Oops I meant paywall-friendly. I guess it autocorrected... I'll time box it

**Comment by cellog** [comment]
Here is the draft PR experiment showing what I had in mind: https://github.com/unlock-protocol/unlock/pull/1683
