### ISSUE TITLE
Having to add `--no-verify` every time I push a branch

### ISSUE THREAD

**Issue by nfurfaro** [unlock-protocol/unlock#1962]
Every time I try to push a branch to the unlock repo I get this message:
```
Oops! Something went wrong! :(

ESLint: 5.12.0.
No files matching the pattern "unlock-app/rollup.paywall.config.js" were found.
Please check for typing mistakes in the pattern.

husky > pre-push hook failed (add --no-verify to bypass)
error: failed to push some refs to 'https://github.com/unlock-protocol/unlock.git'
```
I'd like to know why this is the case, and whether it's specific to my setup or if others see the same thing? adding the `--no-verify` works...but it feels like I may be bypassing some safety feature I don't understand.

**Comment by akeem** [comment]
@nfurfaro interesting, does this file exist for you locally? 
It looks like it exists currently in master https://github.com/unlock-protocol/unlock/blob/master/unlock-app/rollup.paywall.config.js

**Comment by cellog** [comment]
the problem is the regex in the husky script. It's too vague. Someone with regex wizard skills needs to update it to only match the subdirectories it is trying to match. Now, it matches any files that are in the current directory.

So, if you have changed a file in paywall, and also have a modified file in unlock-app with `paywall` anywhere in the name, that will also match.

I don't understand why that happens every time for you though

**Comment by nfurfaro** [comment]
@akeem Yes, this file does exist for me locally. I've never touched it, or anything to do with the paywall.
![image](https://user-images.githubusercontent.com/17053076/54044748-f7323380-418c-11e9-9387-1e013583a62b.png)
