### ISSUE TITLE
README of integration tests needs a small update

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#1968]
In order to get the integration tests working where we create a viable lock for use in a paywall test, the README needs an update.

Basically, we need to deploy the unlock contract from within `unlock-app` now instead of `smart-contracts` with:

```
npm run deploy-unlock-contract
```

With these changes, everything works

**Comment by akeem** [comment]
tbh we should not codify this the readme, as this will cause downstream issues based on the location of the deployed Unlock contract differing between CI and development environment. 

The likelihood of someone doing this and updating a lock address within the test to one that doesn't exist is extremely high. I've punted on this in order to get us to a place where the test work.

Let's work on getting the deployment addresses between CI and development similar and we can remove this burden from future developers completely

**Comment by cellog** [comment]
Sounds good. Hoping to get a working local build soon, can you slack me the script you're using when you have a chance? Maybe that will get my local setup working
