### ISSUE TITLE
Swap `disable` features for OZ `Pausable`

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#2080]
**Is your feature request related to a problem? Please describe.**
We have a feature implemented, `isAlive` / `disableLock` which is similar to a feature available in the OpenZeppelin library.

**Describe the solution you'd like**
Consider switching to use https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/lifecycle/Pausable.sol

**Describe alternatives you've considered**
n/a

**Additional context**
This will change has a few implications that may make us decide against this change:
 - It will cost more gas to create a new lock since this will add more bytecode to the contract
 - The Lock owner is the only account with permission to pause by default, but they can also add or remove additional accounts
 - The contract can be unpaused after it was paused.  With our currently implementation, once `isAlive` is false that cannot be reversed.

**Comment by hardlydifficult** [comment]
What do you think @nfurfaro

**Comment by hardlydifficult** [comment]
Or maybe we use https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721Pausable.sol

**Comment by nfurfaro** [comment]
I'm thinking that using `Pausable.sol` would probably make more sense here as we already have our own custom erc721 implementation. But, for the added gas cost, not sure if the benefits are worth it? 
Benefits:
- using audited code rather than rolling our own
  (but it's pretty simple code to review and feel confident about)
- the ability to unpause...if we need this. For now, the only reason someone would disable a lock is to deprecate/migrate it. Being able to toggle the isAlive state would be useful under certain circumstances, but I don't know if that applies to our contract.

**Comment by julien51** [comment]
This looks like a good idea to me.
Agree that there are no huge benefits though so probably pushing that down the TODO stack ;)
