### ISSUE TITLE
refactor environment variables to use a consistent naming and system.

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2149]
As mentioned in #2143, environment variables like `LOCKSMITH_URI` `PAYWALL_URL` `UNLOCK_HOST` are inconsistent. this issue is a place to discuss the ways to unify them.

For example, `PAYWALL_URL` and `PAYWALL_SCRIPT_URL` can be split into `PAYWALL_HOST`, `PAYWALL_PATH` and `PAYWALL_SCRIPT_PATH`, however, we also need the full origin (i.e. is it http or https?) so do we use `PAYWALL_ORIGIN` in this case? `LOCKSMITH_URI` is similar, in that it is a base upon which other URLs are built, and is also an origin

`HTTP_PROVIDER` is a full URL

(etc.)

let the discussion ensue, amen

**Comment by julien51** [comment]
I think this is indeed required and we will have to think about how this is handled accross all apps.
The naming is probably the easier part (or at least easy to fix our current naming issues!)

The way I am thinking about this:
* each application list a set of required ENV variables it needs in order to work
* these ENV variables have different values in different envs (test, dev, staging, production)
* each application can set *default* values for dev/test but staging and production should be explicitly set

**Comment by cellog** [comment]
To address the current problem with naming issues (and the fact that our current `README` suggests a setup that does not work), I suggest we do these with the env variables:

1. We define app root origins as `ORIGIN_<APP NAME>`
2. all URLs are calculated relative to these origins (`DASHBOARD_URL`, `USER_IFRAME_URL` go away)
3. env variables needed across apps are prefixed with `APP_`, and if they only apply to one app, that is a part of the prefix (`APP_LOCKSMITH_`)
4. env variables needed only in development are prefixed with `DEV_` so we aren't tempted to add them to circle.
5. variables start with their category (`ORIGIN_` or `ADDRESS_` for example) if there are more than 1 of that type.

Naming notes:
1. We have several names for a provider of an ethereum blockchain (`HTTP_PROVIDER`, `READ_ONLY_PROVIDER`). This consolidates them all into `ETHEREUM` as in `HOST_ETHEREUM` and `ORIGIN_ETHEREUM`
2. The purchase env variables for locksmith become `APP_LOCKSMITH_PRIVATE_KEY_PURCHASER` and `DEV_ADDRESS_PURCHASER` since the latter is only used in development to transfer some erc20 and the former is used in both envs to make key purchases on the chain (this was missing from the docs as well)
3. The bootstrap env variable is disambiguated to specify that it is bootstrapping eth. Incidentally, this value is not actually used in the bootstrap script (10 eth is hard-coded), so that will need to be changed too.

Here is what the suggested `.env.dev.local` would look like

```
# origin of apps and of the ethereum blockchain (ganache in development)
ORIGIN_DASHBOARD=http://localhost:3000
ORIGIN_PAYWALL=http://localhost:3001
ORIGIN_STATIC=http://localhost:3002
ORIGIN_TICKETS=http://localhost:3003
ORIGIN_WEDLOCKS=http://localhost:1337
ORIGIN_LOCKSMITH=http://localhost:8080
ORIGIN_ETHEREUM=http://localhost:8545
# environment variables shared between apps
APP_ERC20_SYMBOL=DAI
APP_ADDRESS_ERC20_CONTRACT=0x591AD9066603f5499d12fF4bC207e2f577448c46
# app-specific environment variables
APP_DASHBOARD_STRIPE_API_KEY=<put in a valid Stripe testing API KEY (https://stripe.com/docs/keys)>
APP_LOCKSMITH_PRIVATE_KEY_PURCHASER=<private key for the locksmith purchaser>
# development-specific environment variables, not used in production
DEV_HOST_ETHEREUM=127.0.0.1
DEV_PORT_ETHEREUM=8545
DEV_ETHER_BOOTSTRAP_AMOUNT=15.0
DEV_ADDRESS_ETHEREUM=<your ethereum address>
DEV_ADDRESS_PURCHASER=0xe29ec42f0b620b1c9a716f79a02e9dc5a5f5f98a
```

@julien51 please take a look when you get a chance.

**Comment by julien51** [comment]
> We define app root origins as ORIGIN_<APP NAME>
> all URLs are calculated relative to these origins (DASHBOARD_URL, USER_IFRAME_URL go away)

I am in strong favor of using a single variable name for each app and use it to derive all "sub" urls and I agree we should use a "standard" naming convention, maybe `*_BASE` instead of `ORIGIN`. This may bot be clear with `DASHBOARD_URL` was actually supposed to be a base/origin ;)

> env variables needed across apps are prefixed with APP_, and if they only apply to one app, that is a part of the prefix (APP_LOCKSMITH_)
I am not sure prefixing with `APP` makes sense because we will inevitably see env vars end up being re-used in multiple apps which will lead to confusion.

> env variables needed only in development are prefixed with DEV_ so we aren't tempted to add them to circle.
I strongly think we should not have _any_ development only variable. This is a big code smell IMO.

> variables start with their category (ORIGIN_ or ADDRESS_ for example) if there are more than 1 of that type.
I like the idea of having the "type" (URL vs HOST) of the env variable being explicit in the name.

> We have several names for a provider of an ethereum blockchain (HTTP_PROVIDER, READ_ONLY_PROVIDER). This consolidates them all into ETHEREUM as in HOST_ETHEREUM and ORIGIN_ETHEREUM
hum... I am not sure this gains in clarity here. 

> The purchase env variables for locksmith become APP_LOCKSMITH_PRIVATE_KEY_PURCHASER and DEV_ADDRESS_PURCHASER since the latter is only used in development to transfer some erc20 and the former is used in both envs to make key purchases on the chain (this was missing from the docs as well)
For APP_LOCKSMITH_PRIVATE_KEY_PURCHASER see my comment above. We could eventually have another app which would need that variable. "forcing" the `LOCKSMITH` in the name may end up counter productive because then we end up with a name that is not accurate or a duplicate value.

> The bootstrap env variable is disambiguated to specify that it is bootstrapping eth. Incidentally, this value is not actually used in the bootstrap script (10 eth is hard-coded), so that will need to be changed too.
This makes me think that we should only add as env variable stuff that is strictly required as environment variables and that may be the toughest thing to enforce. I believe we already have way too many and most of them don't add very much value.
I think each application should have its own set of "variables" which are not resulting from the environment itself. The bootstrap amount is a good example of that.

**Comment by cellog** [comment]
`_BASE` could work. I much prefer `ORIGIN` because of https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin

As for not having any dev-only config variables, how would you suggest we pass in things like the user's ethereum address?

**Comment by julien51** [comment]
@clemsos is working on this :)
