### ISSUE TITLE
eslint/prettier conflicts

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#2151]
running `npm run eslint-check` in `unlock-app` reveals a conflict between eslint and prettier: the `linebreak-style` rule. This should be removed from `.eslintrc`

**Comment by julien51** [comment]
Good cacth! I think we should make sure the eslint rules have precedence over the prettier rules in general... so we should probably do the opposite and change the prettier config. Thanks!

**Comment by cellog** [comment]
The prettier docs recommend removing eslint rules that conflict, I can paste the link later if you'd like, on my phone atm

**Comment by julien51** [comment]
I am not surprised that this is what prettier recommands but I think we should consider them partial here ;p
Honestly, linting is a lot more important than "prettifying" so I think we should consistently favor eslint over prettify when we can. 

But even before we decide that one needs to go away in favor of the other, I'd love to understand what is going on. We have been using the 2 for a couple of months and I cannot remember any recent conflicts (the setup was non trivial... but since then it worked great?). 

Could you investigate and explain what is going on exactly?

**Comment by cellog** [comment]
The point of prettier is to enforce visual style, and this overlaps with those portions of eslint. It doesn't have anything to do with them being partial, it is that eslint is designed to find all kinds of problems, and to fix problems. prettier is more opinionated than eslint is, which makes our style more consistent (eslint allows 2 differing styles to slip through in many, many cases).

eslint is great for catching things like unused variables and other logic errors. This is the reason we use them.

Thus, we should not rely upon eslint for any styling unless we remove prettier.

I suspect the problem is that prettier is using different parsers locally. There is both a babel and a typescript parser, I'm experimenting with making it explicit to see if that fixes the issue

**Comment by cellog** [comment]
since the basic premise is not agreed upon, I am closing this issue.
