### ISSUE TITLE
Switch to transfer ERC20 tokens directly to the Lock owner's account

### ISSUE THREAD

**Issue by hardlydifficult** [unlock-protocol/unlock#2200]
Today, ERC20 locks deposit funds from a purchase into the contract (similar to ETH locks).  We could instead move the tokens directly into the Lock creator's account.

For this, we would:
 - Require the Lock owner has a token allowance on createLock
 - When transfers occur, move funds directly into the Lock owner's account
 - When a refund occurs, it's transferred from the Lock owner's account to the Key owner's account
 - Remove withdraw support on ERC20 Locks (or just leave it as a no-op)

Risk: similar to how an ETH Lock owner may withdraw too much, if the ERC20 Lock owner moves funds out of their wallet or cancels the approval then we are unable to pay refunds.  The difference here is that it may be less apparent to the Lock owner that they may be preventing refunds making a transfer from their account.

**Comment by julien51** [comment]
I was about to raise the issue around cancellations. I'd be in favor of keeping the 2 distinct for now, but we can reconsider later if this becomes an issue for creators.

I also think we should have a consistent behavior for both types of locks (ERC20 vs eth) and since it would be more costly to transfer the eth directly to the lock owner, this means we need to keep the balance under the contract's address. 

Finally I think there is a UI benefit in being able to quickly show the balance on their lock rather than go grab all past transactions and sum them (even though once the creator withdrew once this is less true).

closing for now!
