### ISSUE TITLE
Flaky test: "The Unlock Paywall › after key purchase, unlocked flag appears"

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#2605]
**Describe the bug**
The integration test for the paywall flag appearing after key purchase may fail or succeed on different runs against the same code.

[Failing test](https://circleci.com/gh/unlock-protocol/unlock/25606?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

[Passing test](https://circleci.com/gh/unlock-protocol/unlock/25660?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

No changes were made to code that impacts the Paywall in this PR, and no code was changed between these 2 runs.

**Comment by cellog** [comment]
the only thing I see in the logs that may be considered a possible clue is that after the key purchase transaction, nothing is requesting the transaction. So, for example, here is the log for a successful lock creation transaction:

```
ganache-integration_1       | 2019-04-11T12:26:59.071052647Z   Transaction: 0x5926c8459d339010c0ffaaf017bf7e013f283a9afee6614e1da9dd98436c84bf
ganache-integration_1       | 2019-04-11T12:26:59.071056659Z   Gas usage: 1744055
ganache-integration_1       | 2019-04-11T12:26:59.071059344Z   Block Number: 93
ganache-integration_1       | 2019-04-11T12:26:59.071073778Z   Block Time: Thu Apr 11 2019 12:26:59 GMT+0000 (Coordinated Universal Time)
ganache-integration_1       | 2019-04-11T12:26:59.071076933Z 
ganache-integration_1       | 2019-04-11T12:26:59.101045055Z eth_getTransactionReceipt
ganache-integration_1       | 2019-04-11T12:26:59.108375382Z eth_blockNumber
ganache-integration_1       | 2019-04-11T12:26:59.110246768Z eth_getTransactionByHash
```

Immediately, the app requests the transaction, receipt and block number.

But the test that failed in the paywall did not request the transaction, suggesting that walletService never got a notification of the transaction hash:

```
ganache-integration_1       | 2019-04-11T12:27:18.517565639Z   Transaction: 0xa46938d5e7095834ee4eeec3cf987604dc3c8e1bd87c4de5be99f144319f4cce
ganache-integration_1       | 2019-04-11T12:27:18.517569471Z   Gas usage: 179196
ganache-integration_1       | 2019-04-11T12:27:18.517572024Z   Block Number: 112
ganache-integration_1       | 2019-04-11T12:27:18.517574503Z   Block Time: Thu Apr 11 2019 12:27:18 GMT+0000 (Coordinated Universal Time)
ganache-integration_1       | 2019-04-11T12:27:18.517577075Z 
ganache-integration_1       | 2019-04-11T12:27:20.251010180Z eth_accounts
ganache-integration_1       | 2019-04-11T12:27:20.457776920Z eth_accounts
```

This could have been caused by a couple of things, most likely is that puppeteer choked on a race condition and closed the page before it could do its thing. I'll keep trying to reproduce.

**Comment by cellog** [comment]
this test has not failed in any builds for the past week, I'm going to close as fixed, re-open if it resurfaces
