### ISSUE TITLE
Paywall does not take into account pending transactions

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#3246]
**Describe the bug**
When purchasing a key on the paywall, if the user immediately refreshes, will the transaction has not been mined yet, the paywall locks again, rather than showing the the "optimistic unlocked banner"

**To Reproduce**
1. Go to http://ouvre-boite.com/members/
2. Click on 'Purchase'
3. Refresh
4. See the paywall

**Comment by cellog** [comment]
this does not happen with current staging, see https://staging-paywall.unlock-protocol.com/demo/0x39B3D5666fab11D609BaF0e953cef469815f7Fbf

**Comment by cellog** [comment]
On ouvre-boite, it fails while parsing the inputs of the retrieved transaction. What contract version was the lock released under?

**Comment by cellog** [comment]
this is the bug we saw the other day: the transaction fails to retrieve from the chain and so it tries to retrieve from defaults

**Comment by cellog** [comment]
The problem is that the transaction is still pending, see https://etherscan.io/tx/0x272e423ef7e6bc289f6d253be2ce8b6ac94a108b6605a946e62470d66eca874e

Thus, retrieving it from the read-only alchemy provider returns null because it does not see it mined yet.

We need to catch this inside web3Service. Basically, if we refresh, then the defaults are gone and boom, byebye
