### ISSUE TITLE
Decrypting an encrypted private key takes approximately forever

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#3297]
**Describe the bug**
Decrypting an encrypted private key has a substantial delay. This is a liability from a UX perspective, because users will want as near as possible immediate response to their actions. A 5-10 second delay before we can start a key purchase transaction, for example, is not good.

We need to find out what we can do to make this process faster.

**Comment by cellog** [comment]
@ricmoo could use your insights on this one

**Comment by ricmoo** [comment]
I don’t know the entire context behind this, but the security liability of not waiting 5-10 seconds is bad. You should try using https://ethers.io and create a wallet there. I find a progress bar and the word “decrypting” helps, since they realize it is for their own safety.

That said, you can of course encrypt things directly (although, if you go this route, talk to me when choosing what to encrypt, because there are lots of side-channel attacks I’ve seen people put in their apps doing this).

The reason we need a delay is to protect brute force attacks. If someone gets a hold of your JSON wallet and it is easy to guess a password, within seconds they will have gotten in. If it takes 10s per “guess”, even a moderately safe password could take years to crack, which is usually not your best value proposition as an attacker, and if a person moves their funds every few months anyways, the point of an attack becomes small.

For example, in my wallets, I generally decrypt once and keep it in secure memory so signing is faster. For Ethers Wallet (iOS), once decrypted, I re-encrypt it against the Secure Enclave, and then when needed the biometrics are needed to fetch it, but this is fast. And if anything seems fishy, I purge it immediately from the Secure Enclave. It does mean the next time they send a transaction, they will have to wait again, but a small price to pay for added security. :)

**Comment by cnasc** [comment]
> the security liability of not waiting 5-10 seconds is bad

@ricmoo could you give us a little more info regarding this strategy? If I understand correctly, the encrypted wallet is just the standard Keystore V3 format. So the delay of 5-10 seconds is enforced only by `ethers`?

To play an adversary here for a moment, if I get a hold of someone's encrypted wallet and I wanted to attempt a brute force on it, what stops me from just using a different tool to decrypt it?

**Comment by ricmoo** [comment]
It is the standard Keystore V3 format, which is what enforces the 5-10 seconds. Ethers, as well as any tool, will try to decrypt is as fast as possible. The "scrypt" algorithm is designed to enforce a delay by being difficult and memory hard. The standard values (N = 1 << 18, r = 8, p = 1) are designed to take about 5-10 seconds, but as hardware gets faster, these values are increased to maintain the 5-10s target.

If you use a different tool, it should take the same amount of time (give or take; C++ tools for example, are much faster, which is more reason it needs to be increased in general, since an attacker is going to use the fastest option).

You can tune the values, for example, set N = (1 << 10) which is basically no protection, in which case the security of the JSON file is basically none.

The 5-10 seconds is enforced by math, not by Ethers or anything else. :)

**Comment by cnasc** [comment]
> The 5-10 seconds is enforced by math, not by Ethers or anything else. :)

Aha, that's what I was missing. Alright, we'll just have to have a loading spinner then, since it looks like there's no way around it. Thank you for helping us understand @ricmoo!

**Comment by ricmoo** [comment]
Well, you can of course eliminate it, just keep in mind you are putting your customer's security at risk.

It is a balancing game. If the average customer will only have $10 worth of ether ever in the account, or if there is a reliable way to recover stolen fund, it can be eliminated. It depends very much on the economic incentives and safety bounds you are trying to achieve. Again, not exactly sure what you are trying to protect, but it is always a balance between UX and security. :)

**Comment by cnasc** [comment]
The case we're providing here is a sort of "proxy wallet," which we host on behalf of users. The wallets themselves hold keys to lock smart contracts, but should never actually hold any eth (unless the user "ejects" their account and takes control of the wallet, in which case they can use it like any other crypto wallet).

We can look into doing a different tradeoff, but probably for the time being it's best to go with the standard workflow.

**Comment by cnasc** [comment]
I wanted to check up on the difference between what we previously had with the `web3.js` default vs. what we have now after migrating to `ethers`. 

`web3` had N = 1 << 13, which is a pretty sharp drop from the N = 1 << 18 in `ethers`, and which allowed us to decrypt an account _very_ quickly (which was the source of my confusion -- I expected that both libraries would have pretty similar defaults)

**Comment by ricmoo** [comment]
That is a very old default value (it is roughly 32x faster). I believe the current values for Geth are (1 << 18) and for `--weak-kdf` it uses (1 << 17). You can use any power of 2 you wish, but that directly corresponds to the level of protection from brute force attacks.

I personally have keys set up that require over 1 month of CPU time to compute, but that is for fairly obscure and experimental reasons. :)

Keep in mind the values used are per-wallet. I also have some testnet wallets with (1 << 12) for testing purposes. When importing, they are super fast, but it only holds testnet ether.
