### ISSUE TITLE
Use a price oracle to determine GDP in Unlock.sol

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#3711]
**Is your feature request related to a problem? Please describe.**
Today the GDP calculation sums ETH and ERC20 tokens as if they were the same units.  That means the GDP value we have ATM is worthless.

Fixing this is required in order to properly mint Unlock Discount Tokens.

**Describe the solution you'd like**
Consider https://github.com/marbleprotocol/polaris or other solution to determine the value of an ERC20 token, and use that when updating the GDP.

If the token is not tracked by the oracle, I think we can assume 0 and carry on.

**Describe alternatives you've considered**

**Additional context**

**Comment by julien51** [comment]
Looks promising! I was initially thinking about using the data from Uniswap, but I guess this is similar? I think it is important that we're able to eventually change approach if needed...

**Comment by hardlydifficult** [comment]
Polaris fronts the Uniswap contracts - simplifies the API for us and avoids an attack vector.
In terms of being able to change in the future, if Unlock.sol implements this instead of PublicLock.sol we won't have any trouble swapping it in the future.

**Comment by hardlydifficult** [comment]
Hmm Polaris is expensive. But maybe we can learn from their approach.

**Comment by hardlydifficult** [comment]
Looking into this a bit, going directly to Uniswap should be fine for our use case.  It also seems like it won't be hard to create.

**Comment by hardlydifficult** [comment]
The attack that motivated Polaris, as it would apply to Unlock:

In a single transaction:
  - Buy a ton of DAI, driving up the price
  - Buy a key, mint an unfairly large number of Unlock Discount Tokens since the ETH value of the purchase appears high
   - Sell the remaining DAI, price returns to normal

So basically you can flood the Unlock Discount Token market by minting unlimited tokens.

We could:
 - whitelist major tokens such as DAI.  does not eliminate the risk, but tokens with a lot of liquidity probably won't be attacked due to the cost to do so.
 - or use a method similar to Polaris: periodically cache the price and use a moving average. 
     - we have a ton of hooks we could consider for doing the update ourselves - eliminating the need for their incentive system and therefore eliminating costs (except some gas impact to users). e.g. every purchase causes Unlock to refresh the price if we didn't already in the past x blocks
     - we could also make a call to refresh price that only our bot account can call.  we script a bot to make the call periodically, maybe daily

cc @julien51

**Comment by hardlydifficult** [comment]
Oh! and we could create an incentive system using UDT.  Make the call to refresh price something that anyone can call. The first one to call it when a refresh is warranted (i.e. it's been x blocks since the last refresh) than pay that person y UDT for their contribution.  We can still write a bot for it - and maybe the community takes over long term.

**Comment by julien51** [comment]
> So basically you can flood the Unlock Discount Token market by minting unlimited tokens.

I think it is actually not trivial to do: any given lock can only trigger so many UDT to be mined. So that means the attacker would have to purchase a ton of keys on many different locks....? And in the end, for the purpose of artificially inflating the available discount? I am not too worried, at least in the short term, so maybe we can use Uniswap directly for now and change the mechanism later?

**Comment by julien51** [comment]
> we have a ton of hooks we could consider for doing the update ourselves - eliminating the need for their incentive system and therefore eliminating costs (except some gas impact to users). e.g. every purchase causes Unlock to refresh the price if we didn't already in the past x blocks

Seems like a decent approach too actually. Whatever is simplest to get started?

**Comment by julien51** [comment]
We should decrease GDP on key cancellation, always in Eth, taking the current day's Ether price (even if it is different from the one at purchase time)

**Comment by julien51** [comment]
And yes, we want to a function (which we can remove later) which would let the Unlock admin (us for now) to reset the GDP to any arbitrary value.

**Comment by NickCuso** [comment]
Why Ether instead of Dai?  It seems all the most common tokens have a dai market which should allow for a direct conversion.  And given the volatility of ether it seems dai would better suit our goals.
