### ISSUE TITLE
Tests coverage

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#38]
We need a way to run full test coverage across all code and include coverage on the main README page.

**Comment by hardlydifficult** [comment]
I could take this on for the smart-contracts only.  I would use solidity-coverage to report to coveralls.io.  Once in place, we can add rules to:
 - Block pull requests which do not have at least x% covered (and we can increase x periodically overtime)
 - Block pull requests which reduce coverage by x (where x could be 0).

And coveralls supports a badge for the README page.

Let me know if I should proceed with this.

**Comment by hardlydifficult** [comment]
Sounds good.  Note that `solidity-coverage` is very slow and will increase our Travis build times.

**Comment by hardlydifficult** [comment]
solidity-coverage fails to execute the unit tests (https://travis-ci.com/hardlydifficult/unlock/builds/97865178#L1995) with the following errors:

 - Revert reason is not known (https://github.com/sc-forks/solidity-coverage/issues/305)
   - Proposed fix: when we add a `shouldFail` helper method (https://github.com/unlock-protocol/unlock/issues/1106), we can skip the message check when testing coverage (but keep the expect fail check).  This does mean we will need our own `shouldFail` implementation instead of using openzeppelin's directly.
 - Different bignumber implementation
   - Proposed fix: always explicitly use bignumber.js
 - `The parameter "[object Object]" must be a valid HEX string.`
   - not sure what this one is yet

**Comment by hardlydifficult** [comment]
Getting close to enabling `solidity-coverage`.  For now, here's the report on our current status:
```
-----------------------|----------|----------|----------|----------|----------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------|----------|----------|----------|----------|----------------|
 contracts/            |    93.86 |    75.81 |    92.86 |    92.65 |                |
  PublicLock.sol       |    98.85 |    84.62 |      100 |     98.1 |        540,576 |
  Unlock.sol           |    83.33 |       50 |    83.33 |    85.71 |        170,171 |
  UnlockTestV2.sol     |      100 |       50 |      100 |      100 |                |
  UnlockTestV3.sol     |       60 |    16.67 |       60 |       50 |... 55,56,57,58 |
 contracts/interfaces/ |      100 |      100 |      100 |      100 |                |
  IERC721.sol          |      100 |      100 |      100 |      100 |                |
  IERC721Receiver.sol  |      100 |      100 |      100 |      100 |                |
  ILockCore.sol        |      100 |      100 |      100 |      100 |                |
  IUnlock.sol          |      100 |      100 |      100 |      100 |                |
-----------------------|----------|----------|----------|----------|----------------|
All files              |    93.86 |    75.81 |    92.86 |    92.65 |                |
-----------------------|----------|----------|----------|----------|----------------|
```

**Comment by hardlydifficult** [comment]
Quick update: solidity-coverage was running, but now builds fail with `Invalid number of arguments to Solidity function`.  I'm not sure what changed to cause this yet... going to diff the last working build vs master and go from there.

**Comment by hardlydifficult** [comment]
solidity-coverage now included.

Next step: publish reports to `coveralls.io` (?)
@julien51 we'll need the repo_token from coveralls, then I can update the travis build to publish the report.  

Once we have that in place we can configure the rules and make this a required check for PRs.

**Comment by julien51** [comment]
Great job on this @hardlydifficult!
Please tell me more about `repo_token` ? What is it?

Also I think we should have a mechanism to "enforce" the levels. For example we set global coverage levels of coverage for statements, functions and lines which we slowly increase over time.
for starters we can set them at  93%, 92%  and 92% respectively?

**Comment by hardlydifficult** [comment]
Per docs looks like we could use coveralls.io or codecov.io - I have experience with coveralls, but have heard that codecov is nicer.

When you create an account on one of those sites, there will be an environment variable we need to add in order to publish reports from Travis.  That's the `repo_token`, but codecov calls it the `UploadToken`.

Yea codecov looks great poking around the docs, e.g. they have a bot which can be configured to post a comment on the PR only if the coverage changed https://docs.codecov.io/docs/pull-request-comments

Both sites allow commit status rules (which publish status that you can then set as required in GitHub) - they use a single coverage number (merging line coverage and branch coverage results) and we can assign a threshold, then increase that threshold overtime.  Plus we can have a rule that says it's an error if coverage drops by x% or more in a single PR (e.g. assign that to 0 and new features always require 100% coverage).

Here's the guide:
https://docs.codecov.io/docs/quick-start
However if you create an account and get that token I believe I could run with it from there.

**Comment by hardlydifficult** [comment]
Ohhhh and this is sexy https://www.youtube.com/watch?v=j1eWBa3rWH8&feature=youtu.be&t=51

**Comment by hardlydifficult** [comment]
hmm is this a one-click setup tool? https://github.com/integration/codecov

**Comment by hardlydifficult** [comment]
We removed `solidity-coverage` because it does not support solc5.
However I just found that LeadDAO has cloned and updated it to support solc5.  We could give that a shot.

Or the 0x team has released a coverage tool as well.  They are currently working on adding Ganache support, once in we could try that one.
