### ISSUE TITLE
View list of keys on a lock

### ISSUE THREAD

**Issue by benwerd** [unlock-protocol/unlock#391]

**Comment by julien51** [comment]
This will be complete when https://github.com/unlock-protocol/unlock/issues/465 has been solved!

**Comment by julien51** [comment]
It _looks_ like the UI part has been implemented and merged in https://github.com/unlock-protocol/unlock/issues/465

But something weird is going on because here is what it looks like on staging for a lock with 5 keys sold:
<img width="1613" alt="screenshot 2019-01-14 at 10 34 47" src="https://user-images.githubusercontent.com/17735/51122545-201af580-17e8-11e9-9d6a-37ad24f41c07.png">

**Comment by akeem** [comment]
Investigating

**Comment by julien51** [comment]
Ok, after checking things it looks like there are several missing blocks.
The first one is basically that we get the keys from the `keys` store and filter them. Since we never actually fetch the list of keys this will not take us very far...

**Comment by julien51** [comment]
I will work on the web3Service function to list keys by page first, while @akeem works on the solidity function to return a "page" of owners.
We'll plug that into the redux store after this.

**Comment by julien51** [comment]
Scratch that, the web3Service function `getKeysForLockOnPage` already exist! 
Looking at the redux store now then!

**Comment by nfurfaro** [comment]
@julien51 @akeem I have that functionality  (return a page of owners )written already if it's helpful...

**Comment by akeem** [comment]
@nfurfaro thanks for pointing this out, this is super helpful!

**Comment by nfurfaro** [comment]
@akeem NP.

**Comment by julien51** [comment]
This feature is now working and live. @akeem will finish refactoring the key listing function though to make it slightly more efficient!
