### ISSUE TITLE
For ad remover paywall, the checkout window pops up immediately

### ISSUE THREAD

**Issue by cellog** [unlock-protocol/unlock#4333]
This is a regression. The checkout window should not pop up unless the user explicitly requests to open it on an ad remover paywall.

The regression is probably here:

https://github.com/unlock-protocol/unlock/pull/4315/files#diff-f9b40e8d4fb4b106ccca61ea36807271R187

The checkout iframe should only be shown if it was already visible prior to the account iframe being hidden

**Comment by cnasc** [comment]
Looks like the issue comes in here:

https://github.com/unlock-protocol/unlock/blob/198451465eefbafe6bedf27745c552304e4a25f3/unlock-app/src/middlewares/postOfficeMiddleware.ts#L46-L49

In the MetaMask case, the account iframe sends the account address (even though it isn't necessary) which triggers the (already hidden) account iframe to hide, which causes the checkout to show. The real solution to this is simply not to load the account iframe when we don't need it, which will also solve several other problems.
