### ISSUE TITLE
add a no-close option to the paywall

### ISSUE THREAD

**Issue by cnasc** [unlock-protocol/unlock#4371]
At the moment, we have two "types" that the paywall can be, `adblock` and `paywall`. Semantically these are a bit too specific (and make it sound like those are the only things that can be done, even though the paywall is much more general than that). We should consider replacing these options with a single boolean option, `no-close` which indicates whether the checkout modal can be dismissed or not.

**Comment by cellog** [comment]
This makes a lot of sense. I worry about feature creep without first having a larger discussion about what we want the paywall to look like. Maybe we can meet when I'm back in New York next week for about 30 minutes max and talk about what we'd like to do here.

The thing I like about Chris's approach is that it defines features rather than the type.

Perhaps instead of overloading `type` we could define what kinds of things we want the checkout UI to do.

Examples off the top of my head (I'm spitballing):

- show checkout UI on page load
- prevent user dismissal of checkout UI until the content is unlocked
- show checkout UI on 3rd visit (leaky paywall)

None of these fit cleanly into a "type" but can be combined to create the behavior of paywall types.

**Comment by julien51** [comment]
> The thing I like about Chris's approach is that it defines features rather than the type.

Agreed. I think the "type" should go away.

> show checkout UI on page load
This is probably easily implementable by the creator (using onload events...), so no need to do that ourselves.

> prevent user dismissal of checkout UI until the content is unlocked
Something we should implement because it is not doable by the implementer.

> show checkout UI on 3rd visit (leaky paywall)
Same as first point. Let's now leave that to the creator.

**Comment by julien51** [comment]
Implemented in https://github.com/unlock-protocol/unlock/pull/4424
