### ISSUE TITLE
Using deeplinks in the "no wallet modal"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4379]
When a user who does not have a crypto wallet in their web browser loads the checkout modal, they see a message inviting them to download a crypto wallet (we currently offer Metamask, Coinbase Wallet or Opera). 

We should try to make the links "deep links" (at least on mobile) so that if the user has a crypto wallet installed, clicking on the icon will open the corresponding app on the corresponding page. Similarly if the user does not have the corresponding app installed locally, we would open the corresponding app/play store so the user can install the app.

**Comment by cellog** [comment]
I did quite a bit of digging into this, and the short answer is no, we can't do this.

The longer answer is that coinbase wallet does support deep links, but only for pages shared from within the coinbase wallet app (tap the hamburger menu, and "share"). They don't have a standard way to generate the deep links. I *believe* they are using https://branch.io to support their deep links, because they all go to a website named d3eo.test-app.link, which is mentioned in the app info on android. This website redirects to https://wallet.coinbase.com, and if you append a hash generated by the share feature, it also appends something like https://wallet.coinbase.com/?_branch_match_id=616820615112417270

Beyond this, I dug through their discord channel, and there have been many requests for deep linking. One dev replied in late 2018 that deep linking was on the roadmap, but every request for the next year has gone unanswered.

Julien, if you have contacts at Coinbase you can ping about this, it could unblock it.

**Comment by julien51** [comment]
Ok, I'll try but my main contact there left a couple of weeks ago...
