### ISSUE TITLE
Support a PublicLock owner role

### ISSUE THREAD

**Issue by NickCuso** [unlock-protocol/unlock#4521]
**Is your feature request related to a problem? Please describe.**
An example use-case for the purchase/refund hook is to adjust the price with each purchase.  For this the contract needs to have privileges to updatePrice.

**Describe the solution you'd like**
Use the OpenZeppelin roles pattern in order to support multiple owners.  This way the contract can be added without interrupting any other processes.

**Describe alternatives you've considered**
2) a simple transferOwnershipBack command in the hook contract hard-coded to work with PublicLock for that specific command or 3) support arbitrary calls from the owner of the hook contract.

**Additional context**

**Comment by nfurfaro** [comment]
@NickCuso I want to make sure I understand this fully before implementing.

1.) As far as following the OZ roles pattern, this seems clear enough. As OZ doesn't have an existing `OwnerRole`, we create one following the pattern established by other roles such as `SignerRole`

2.) As far as the flow of this process would go, it's a little foggy to me still. I'll outline it here and maybe you can help to set me straight.
  a.) Bob purchases a key from a lock.
  b.) `_onKeySold` is called to inform the hook (if there is one registered with the 1820 registry).
  c.) If a hook has been registered, it would be called now, and could then take some arbitrary action, such as updating the `keyPrice`. In order to do so currently, the hook contract would need to be the lock owner. However, if we support an `OwnerRole`, the hook could have this role and therefore update the price. In the `updateKeyPricing` function, we would remove the existing `onlyOwner` modifier and replace it with an `onlyOwnerRole` (or similar) modifier.

3.) Have we actually registered any hooks yet, or just laid the groundwork to be able to do so?

We could achieve "dynamic pricing" by using a bonding curve, but I'm guessing the motivation behind creating an OwnerRole is more general-purpose than just a single use case such as being able to update the price automatically.

**Comment by NickCuso** [comment]
yea that sounds about right.  but the hook is based on the beneficiary, not the owner.
