### ISSUE TITLE
Identify failure when creating a duplicate account

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4547]
We should make sure we handle the case when users try to create a second account with the same email address (I suspect I tried to do that and got an error which did not indicate that).

**Comment by cnasc** [comment]
At the moment, whenever we have a failure to create a user account, there will be an error that says `Could not create this user account.`

Is this primarily a matter of wording? There should only be 2 failure cases as I understand:

- couldn't write the record to the DB (most likely caused by there already being a record with that email)
- payload didn't contain user information (should never happen through our frontend)

**Comment by julien51** [comment]
This has been implemented!
