### ISSUE TITLE
Check your wallet!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4707]
When opening the checkout modal it is possible that the application might not have been "connected" by allowing it in the web3 wallet. If that's the case, we should show a message to the user asking them to check their wallet.

**Comment by cnasc** [comment]
At the moment, the checkout modal simply uses the absence of an account address to show the "no wallet" message. It has no knowledge of whether or not the browser has a web3 wallet.

That's a bit blunt, because there are really two cases:

1. There is no web3 wallet available (the case it handles now)
2. There is a web3 wallet, but it hasn't been enabled (the case in this issue)

One way to solve this would be to pass the checkout the `hasWallet` property that the Wallet object in the main window has. However, that would swell the (already very large) `CheckoutContent` a lot.
