### ISSUE TITLE
Move User Account Lock approval process on chain

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#4753]
As part of moving quickly with the approval process of onboarding Locks to the User Accounts/managed account flow it became clear that we could probably move this on chain and gain a few benefits along the way.

The contract should provide the ability to store a mapping where the approved lock address is the key and associated metadata are the respective values. 

The Unlock multisig wallet should be the owner of this contract. We should ensure that we also capture the revocation of approval and that appropriate data is readable

**Comment by NickCuso** [comment]
Something like `mapping(address => bytes) lockToMetadata`?

hmm what's the benefit of moving this on-chain?

**Comment by akeem** [comment]
@NickCuso  it would be more of an operational improvement than anything else, eliminating the need for managing roles to determine who can update and audibility as we get this for close to for free by moving this on chain

**Comment by NickCuso** [comment]
Something like this should work
```
pragma solidity 0.5.11;

import 'openzeppelin-eth/contracts/access/roles/WhitelistedRole.sol';


contract AccountApprovals is
  WhitelistedRole
{
  mapping(address => bytes) public accountData;

  event Approve(address indexed operator, address indexed account, bytes data);

  function approve(
    address _account,
    bytes calldata _data
  ) external
    onlyWhitelisted
  {
    accountData[_account] = _data;
    emit Approve(msg.sender, _account, _data);
  }
}
```

**Comment by julien51** [comment]
@akeem suggested a new approach to the whole credit card flow, which I am going to try to summarize here before closing this issue (and opening new ones).

Rather than purchase keys on behalf of users, the locksmith purchaser will grant free keys (the lock owner will need to be able to do that!). We will then grant free keys to users who have paid us using other means (credit cards or...). These keys are not transferable or cancellable by their owners, but only by the grantor.

We collect payment in a completely independent way and will send funds to the lock on a different schedule, minus fees that we will take on the creator side, rather than the consumer side.
