### ISSUE TITLE
After log in, do not let ther user purchase again 

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4934]
When using user accounts, the user is rightfully asked to log in when clicking on a "purchase" button.

Once logged in though, the user should not be able to purchase the same key again (or at least the UI should not invite them to do so!) and the paywall should just show the checkout modal with the list of locks (including the one for which the user already has a key with thr right info it)

**Comment by cnasc** [comment]
#4941 provided a mitigation for this, but there is a degree of latency between logging in and unlocking the page that still causes the purchase confirmation to show.

In more detail:
- the page starts locked (because we use the default `0x0000...` address that holds no keys)
- the user logs in
- the page remains locked until the paywall finds the user's existing key, during which time the purchase confirmation is visible for a few seconds
- the page unlocks and the purchase confirmation is replaced by the message indicating the user already has a key

**Comment by julien51** [comment]
That seems like a decent idea.

**Comment by julien51** [comment]
I wonder if https://github.com/unlock-protocol/unlock/issues/4949 would also improve this?
