### ISSUE TITLE
DAI lock not showing "Insufficient funds" even though I do not have them?

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#4950]
When using a crypto wallet (MetaMask) with [an account](0x173E1535B113b8dcaFB44DA068e757F142a056f6) which has no Ether and no DAI, we're only showing Insufficient funds for the Ether lock (See https://www.ouvre-boite.com/members/)

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/17735/66251646-7290ad80-e78d-11e9-888b-e91837ea5784.png">

I believe this is a consequence of user accounts where we want to let the user click on a lock to let them purchase with their CC?

**Comment by cnasc** [comment]
Actually, I think the issue is here (or at least, surfaces noticeably here):
https://github.com/unlock-protocol/unlock/blob/master/paywall/src/utils/locks.js#L23-L44

**Comment by cnasc** [comment]
This actually looks like a simple coding error, not all cases are accounted for in the conditional, and it fails open instead of closed.

Essentially, there's nothing in `account.balance[lock.currencyContractAddress]` (line 43), so parsing a float from `undefined` gives `NaN`, which can't meaningfully be compared to numbers.

**Comment by julien51** [comment]
Great catch! Thanks.
