### ISSUE TITLE
Investigate the `checked_is_forked_pr` method?

### ISSUE THREAD

**Issue by akeem** [unlock-protocol/unlock#5813]
@cnasc Raised a valid point that the `check_is_forked_pr` method looks a bit off in the deployment scripts. 

While not extremely urgent this should be looked into.

**Comment by cnasc** [comment]
Some more detail on this:

```bash
# assignment
is_forked_pr=$7

function check_is_forked_pr()
{
    # should be comparison, but is actually assignment
    if [ is_forked_pr = "true" ]; then
        echo "Skipping deployment because this is a pull request from a forked repository."
        exit 0
    fi
}
```

I'm not a bash expert, but from some poking around it looks like `check_is_forked_pr` never does anything because the conditional is never executed. Resolving this is as simple as changing the condition to 

```bash
if [ $is_forked_pr = "true" ]; then
```

By including the sigil, we make it so this function is more than a no-op.

This is something we might have caught if we implemented [shellcheck](https://github.com/unlock-protocol/unlock/issues/4012), even if just as a manual process during development. I'm not sure what the impact of this particular issue is, but it could be indicative of other problems in our shell scripts.

**Comment by akeem** [comment]
Closing at this changes has made its way into master
