### ISSUE TITLE
Staging ticket integration

### ISSUE THREAD

**Issue by ligi** [unlock-protocol/unlock#6228]
currently in staging environment when you click on tickets here:
![Selection_365](https://user-images.githubusercontent.com/111600/76772082-99252c80-67a0-11ea-9a17-fb1081a7696c.png)

you land here:
![Selection_366](https://user-images.githubusercontent.com/111600/76772092-9fb3a400-67a0-11ea-9632-adcce785a4cd.png)

It would be great to also try out ticketing in a staging environment

**Comment by julien51** [comment]
Thanks @ligi for reporting this.
You are correct. We need a staging environment for this... However, we are actually changing our approach to this, because we learned from our users that most of them did not need a page to host the tickets as they'd rather sell tickets from their own sites.

We need to update our documents for this, but the general approach would just be to "embed" our paywall application and button on your site.

I'll write a document for this later today and I'll post it here!

**Comment by julien51** [comment]
Alright, the document is up!
