### ISSUE TITLE
Remove ganache from Ci

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7506]
It still used for integration tests. We can replace by a hardhat node to make things more consistent across the repo

**Comment by julien51** [comment]
Oh yes! We can remove now as integration tests are not running right now though... (we do need to re-enable them though!)

**Comment by clemsos** [comment]
checking I see it is also used by locksmith test suite. Using hardhat via npx should be pretty straightforward - just port number to change hopefully

**Comment by julien51** [comment]
Oh weird, that locksmith uses it. It should not. Let me try to see why and if we can clean this.

**Comment by julien51** [comment]
Actually unlock-js uses ganache. I will see if we can switch to hardhat easily!

**Comment by julien51** [comment]
Ok, so it is tricky,
Unlock-js includes a bunch of unit tests (running with `jest`) which do not need to connect to an EVM node. It also includes a test suite `walletServiceIntegration.test.js` which tests things against an EVM node.

I believe this is *that* specific test that we would need to run with/against hardhat. Since the node needs to have a few things set-up, the test suite starts by calling `__tests__/setup/prepare-ganache-for-unlock.js`. 

What do you think is the easist way to run this with hardhat?

**Comment by clemsos** [comment]
The simplest way will be to run a hardhat node directly from node, using a package like [concurrently](https://www.npmjs.com/package/concurrently) then we can point to the localhost port

**Comment by julien51** [comment]
That's a great idea! I like that!
