### ISSUE TITLE
Remove ability to modify a key manager for an expired key

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#7937]
Since #7797, a key manager should now be pass explicitly each time a key is acquired with the lock `purchase` call. This simplify workflow for 3rd part payment methods (see #7663). However anyone can now re-purchase an expired key and set any address as  key manager. Maybe we should disable the modification of `keyManager` for expired keys?

**Comment by julien51** [comment]
Thanks for raising this @clemsos 
I have been thinking about it a lot and there are 2 approaches:
* disable transfers on expired keys (including transfers by the key manager) but I suspect this won't actually solve much because it the person who wants it could easily purchase it again for the current owner and reset the key manager and transferring it back to them
* consider that this is in fact "expected" behavior. I actually think it is ok to decide that an expired key can be "captured" by anyone. This has a lot of benefits because it solves the problem of the max supply being reached even though some memberships are expired... etc.

I tend to think more and more than the 2nd option is the right one.

**Comment by julien51** [comment]
After consideration, we need to use signatures to make that safe. More soon.

**Comment by julien51** [comment]
We now have fixed this in v11! `purchase` will not extend keys, but create new ones. `extend` cannot change the key manager anymore.
