### ISSUE TITLE
Auto-run npm install when applicable

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#808]
We are not checking in our `node_modules`. This means that when 2 branches diverge on the content of `package.json` we need to explicitly re-install dependencies via `npm install`.
Sometimes, when a developer updates from master, they do not know that one of the merged commits actually updates `package.json` and their local `node_modules` becomes outdated.
Similarly, switching between branches may mean that the content of `node_modules` in one of them is outdated... etc

This is the cause of *many* "bugs" locally in dev which could easily be detected if we had a way to identify that the content of `package.json` (or `package-lock.json`) matches the actual content of `node_modules`.

**Comment by mcernusca** [comment]
What has worked for me in the past is to have the build script make a local package.json copy that lives outside of version control (.package.json.cmp). On build check if these two files match up otherwise prune install and update the local copy. Something like:

```
if ! cmp --silent package.json .package.json.cmp; then
	echo "Removing unused npm modules"
	npm prune
	echo "Installing npm modules"
	npm install

	cp package.json .package.json.cmp
fi
```

Although now that I think about this it might make sense to use package-lock.json file instead of package.json for this now that it exists but I haven't personally tried it.

**Comment by julien51** [comment]
Thanks for this @mcernusca ! I also just read this https://voxpelli.com/2016/07/better-handle-npm-modules/ by @voxpelli and I think we can take some of his ideas into account ;)

**Comment by julien51** [comment]
Same "realm" as https://github.com/unlock-protocol/unlock/issues/728

**Comment by cnasc** [comment]
Given that we're closing #728, I think it's safe to back-burner this one as well
