### ISSUE TITLE
Wrong dollar price displayed for BNB payment

### ISSUE THREAD

**Issue by jerlam06** [unlock-protocol/unlock#8163]
Hi there.

The price displayed just before payment for 0.1BNB in my case, is wrong:
I don't know where these $275 come from, but it is not the price of 0.1BNB at all nor 1BNB.
![image](https://user-images.githubusercontent.com/20628161/151956606-c48d01a8-5d96-46b2-aaf7-1d98c58c851e.png)

**Comment by julien51** [comment]
@jerlam06 Thanks! Do you have the lock address (and network) for which this shows? This would help debug as I suspect we're not using the right currency for the `BNB` ticker.

**Comment by jerlam06** [comment]
Hi @julien51, Yes of course: 0x14cdD9524e02763bdf0B0902034a5568a08f491b

**Comment by julien51** [comment]
Hey, I am so sorry for this. Assigning one of our team members on this so he can check things out!

**Comment by kalidiagne** [comment]
@julien51 

We need to use a different API provider to get the prices, currently, with Coinbase we can't retrieve BNB price, because doesn't support it (like others coins not listed in Coinbase)

<img width="1381" alt="Screenshot 2022-04-04 at 14 03 17" src="https://user-images.githubusercontent.com/20865711/161539968-be7e62f5-0b3e-4bbe-ba08-7b461b409de3.png">

**Comment by julien51** [comment]
We should use Uniswap on each of the networks. I'll write a bit more later.

**Comment by julien51** [comment]
We have now fixed the underlying issue by not showing the price $ until we actually have switched to Uniswap as Coinbase does not support BNB in their pricing API.
