### ISSUE TITLE
Contract verifications

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8190]
Our contracts are all verified on Polygon, BSC, Mainnet, Rinkeby but we do not have the verification for xDAI and Optimism, for new the upgrdadable locks.
We should sort that out.

On Optimism specifically:
Basically the [PublicLock](https://optimistic.etherscan.io/address/0xa9584e6cbaf88c09e5ede06865211ba28febd077) contract is verified, the Unlock contract is verified (both the [proxy](https://optimistic.etherscan.io/address/0x99b1348a9129ac49c6de7F11245773dE2f51fB0c) and the [current implementation](https://optimistic.etherscan.io/address/0x646e373eaf8a4aec31bf62b7fd6fb59296d6cda9#code)), but we are unable to verify the `TransparentUpgradeableProxy` ([example](https://optimistic.etherscan.io/address/0xa6F583B37425A446131EB54C87AeCf2C2BDECeCd)) that actually gets deployed by Unlock (the factory contract).

On xDAI, we have the same issue.

For reference, here is an example of `TransparentUpgradableProxy` [on Polygon](https://polygonscan.com/address/0xfc0FdB39aeA6B599990F050928e97903b10a550d#code)

**Comment by julien51** [comment]
Also I need to add the TranparentProxy addresses to our docs (+ verify)

**Comment by julien51** [comment]
Maybe [Sourcify](https://sourcify.dev/) could help?

**Comment by clemsos** [comment]
OK managed to verify on xdai after all. Documenting the process here ftr

Hardhat was failing. Sometimes returning obscure `API: Unknown UID` from blockscout, sometimes just `Fail - Unable to verify` as a reason.

```
Successfully submitted source code for contract
@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol:TransparentUpgradeableProxy at 0x41BabD1AeE488FCac19cBF28b77dFB820A63209d
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract TransparentUpgradeableProxy without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol:TransparentUpgradeableProxy at 0x41BabD1AeE488FCac19cBF28b77dFB820A63209d
for verification on the block explorer. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/clemsos/Dev/unlock/unlock-alt/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:332:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Environment._runTaskDefinition (/Users/clemsos/Dev/unlock/unlock-alt/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/clemsos/Dev/unlock/unlock-alt/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at main (/Users/clemsos/Dev/unlock/unlock-alt/smart-contracts/scripts/verif.js:41:3)
```

Tried to upload flatten contract using the blockscout UI. I discovered https://abi.hashex.org which is a useful tool to ABI-encode parameters from an existing ABI. Once I extracted all encoded parameters then I submitted on blockscout UI -- but that failed too (silently, without any warning or ui feedback ofc). I tried on Chrome, Brave and Safari because in previous experience the UI was failing on Brave bu working on Safari (?). 
It failed too. 

Then onto the next: Sourcify. There I tried to recompile metadata directly using `solc` directly from @openzeppellin `node_modules` folder but then ended up with conflict in paths. This was solved with the following command :

```shell
solc --base-path=$(pwd) --allow-paths=. --metadata --metadata-literal proxy/transparent/TransparentUpgradeableProxy.sol --pretty-json > metadata.json
``` 

But that was generating broken JSON. I downloaded various package such as `[source-verify](https://www.npmjs.com/package/source-verify)` or `[@ethereum-sourcify/validation](https://www.npmjs.com/package/@ethereum-sourcify/validation)` but none of these worked.

I decided to read `sourcify` source code and stumbled open that line 

https://github.com/ethereum/sourcify/blob/3787d9ddcffb8a45cd5fd5a8092848d06092b135/services/validation/src/ValidationService.ts#L12

which implied the hardhat build files may contain the `metadata.json` output required by sourcify. Turned out that if you fo to `artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.dbg.json` the file looks like this 

```json
{
  "_format": "hh-sol-dbg-1",
  "buildInfo": "../../../../../build-info/ac159a87e647b79e3596d183b61b3d6f.json"
}
```

and you can just drop the file specified in `buildInfo` directly into Sourcify source. It will upload and parse and ask you to specifcy which contract matches with the address. I clicked and it worked !

Note that that manipulation was one of the first thing I triedbut Blockscout won't allow file of size > 10M so that wasn't working.

Thanks for reading, I just needed to vent here !
