### ISSUE TITLE
Lock `setExpirationDuration` should parse infinite duration properly

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8222]
When we create a lock with infinite duration, we set `0` for the `keyDuration`.
Unfortunately that breaks both `getHasValidKey` and `keyExpirationTimestampFor`.
The first one should always return true while the second should return MAX_UINT.
Let's also make sure we disable `shareKey` when the `keyDuration` is 0.

**Comment by julien51** [comment]
Ok so it looks like it is only a problem in the docs which are inacurate! We should not use 0 but MAX_UINT when setting a lock to be with non expiring keys!

**Comment by julien51** [comment]
@clemsos do you mind doing a quick fix in the docs + comments?

**Comment by clemsos** [comment]
so it turns out things work fine but the API is inconsistant with how it works "under the hood", which creates confusion. 

Internally, to make a lock permanent you need to set the lock `expirationDuration` to MAX_UINT. 

Now at the API level, there are 2 functions that does that and they are not consistant. 

1) in the contructor/initializer, you need to pass `0` for param `_expirationDuration` to make the lock becomes "permanent" - i.e. set the `expirationDuration` to MAX_UINT. 

https://github.com/unlock-protocol/unlock/blob/9e20273e1d85c9f13ae067189413d3da7af1e01a/smart-contracts/contracts/mixins/MixinLockCore.sol#L111

2) However, this is not consistant with the `setExpirationDuration` function, which requires to pass MAX_UINT directly.

https://github.com/unlock-protocol/unlock/blob/9e20273e1d85c9f13ae067189413d3da7af1e01a/smart-contracts/contracts/mixins/MixinKeys.sol#L434-L436

Plus, the docstring of the `setExpirationDuration` function states that you need to pass 0 which is plain wrong.

For now, I updated the inline doc but the API should be fixed as well. I think the best fix is to pass `MAX_UINT` everywhere.

FTR the `0` approach was kept because there was this 100 years maximum requirement in the construtor

https://github.com/unlock-protocol/unlock/blob/9e20273e1d85c9f13ae067189413d3da7af1e01a/smart-contracts/contracts/mixins/MixinLockCore.sol#L108

**Comment by julien51** [comment]
> in the contructor/initializer, you need to pass 0 for param _expirationDuration to make the lock becomes "permanent" - i.e. set the expirationDuration to MAX_UINT.

Ha! Indeed, let's try to make it consistent? I think it is ok to pass `MAX_UINT` for `createLock` too?

**Comment by clemsos** [comment]
yes, the best option is to pass `MAX_UINT` to `createLock` so it is consitent with the internals

**Comment by clemsos** [comment]
looking into this, it is actually already possible to pass `MAX_UINT` at creation - currently it is either `0` or `MAX_UINT` to make the lock non-expirable. I think it is just a change in documentation then?  Or should we remove the ability to pass `0` ?
