### ISSUE TITLE
New Website review!

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#8324]
We are getting ready to test the new website! Please help us identify issues, gotchas and things we can improve!
Here is how you can help:

1. Open the [Figma design](https://www.figma.com/file/cksSEyuTPGfHfzRdPosxXw/Unlock-x-DeepWork?node-id=6682%3A2948) in one tab.
2.  Open staging site: https://staging.unlock-protocol.com/
3. Report any discrepancy you might see. Some of them are expected (we changed some of the wording...) but please, report _anything_ that _feels_ off.
4. Click on all links and buttons and make sure they point to the "right" thing (expected based on the button or link's anchor).
5. Feel free to navigate the whole site, not just the landing page and apply the same heuristic as above.

Important: please also test on a a mobile device!

To report issues, the easiest is to open a comment below for _all_ of your comments/issues feedback and create a list using the markdown syntax. @searchableguy and I will update/write inline comments to indicate resolution.

Thanks a lot!

Related: https://github.com/unlock-protocol/unlock/issues/8217

PR: https://github.com/unlock-protocol/unlock/pull/8344

**Comment by julien51** [comment]
- [ ] Replace link when clicking on "Discord" to the [Discord page in the docs](https://docs.unlock-protocol.com/unlock/creators/plugins-and-integrations/discord).
- [ ] "Connect Wallet" Does not do anything. For now, let's replace with "Dashboard" and link  app.unlock-protocol.com

**Comment by searchableguy** [comment]
I couldn't find the doc page on membership. Is it published?

**Comment by desertrat10** [comment]
"invalid date" is showing on the homepage Explore Active Projects-- that might just be a staging thing?
<img width="1167" alt="Screen Shot 2022-03-01 at 5 26 27 PM" src="https://user-images.githubusercontent.com/19274187/156271548-eeb9bcdf-1fb2-4849-a63e-79c342508676.png">

**Comment by desertrat10** [comment]
Change the button copy to "read more on Governance" or "about Governance" if you need a shorter version.
<img width="629" alt="Screen Shot 2022-03-01 at 5 28 48 PM" src="https://user-images.githubusercontent.com/19274187/156271730-90c5a54e-8002-4920-884c-f1bd83e416c0.png">

**Comment by desertrat10** [comment]
The Discord link in the main nav goes to the Guild.xyz homepage.

**Comment by desertrat10** [comment]
Also, this might be a staging thing, on the about page, the News posts all show the same date. Guessing maybe this will import the post date once the site is live?
<img width="745" alt="Screen Shot 2022-03-01 at 5 34 43 PM" src="https://user-images.githubusercontent.com/19274187/156272308-975d0822-d000-42c1-b013-d77d8c4822b8.png">

**Comment by desertrat10** [comment]
On /developers page, the "unlock" should be capitalized. ;)
<img width="1225" alt="Screen Shot 2022-03-01 at 5 37 30 PM" src="https://user-images.githubusercontent.com/19274187/156272490-5fff16ea-3570-4329-9d9b-aec9500b45e7.png">

**Comment by desertrat10** [comment]
This might be nitpicky, but do we want some interaction with the "next page > last page" at the bottom, like a change state on rollover (turns purple)  and/or arrows with the text? And add the "|" in between the words... Next Page | Last Page" ;) 
<img width="1269" alt="Screen Shot 2022-03-01 at 5 43 32 PM" src="https://user-images.githubusercontent.com/19274187/156273126-1d6ea932-44c3-4fbb-9120-c74c52334613.png">

**Comment by desertrat10** [comment]
This is a content thing, feels odd to have the blank space on this block since there's 3 bubbles.
<img width="1185" alt="Screen Shot 2022-03-01 at 5 47 43 PM" src="https://user-images.githubusercontent.com/19274187/156273460-109190c3-8036-4296-9a14-6db1a89e7d8a.png">

**Comment by timfalls** [comment]
The first place I naturally went was "Get Started" (main CTA button). Then, I clicked the "Checkout Unlock Membership" button in the "Try it for yourself" section. 

When the Unlock pop-up window appears upon click, here's the view: 
<img width="1198" alt="Screen Shot 2022-03-01 at 4 36 31 PM" src="https://user-images.githubusercontent.com/806433/156272978-120b7646-c92d-419c-9203-bcdb124b383b.png">

If someone is new to web3, there could be an opportunity to offer some crypto-101 educational content here, for those who might be unsure what all the words mean on this screen. 

eg, "wallet", "gas", and "airdrop" won't be understood by all; so, can we incorporate a call-to-action that offers some background information to those who need it at this stage, to ensure they are successful in "trying it for themselves"? 

This could be a link to a simple web3 basics guide / glossary (Chris and I discussed this and already have a draft) that lives in Docs or on the Blog. 

Bigger Question: are we designing for people who are new to web3, so as to necessitate this kind of instruction; or are we designing for people who already understand these terms?

**Comment by timfalls** [comment]
On the new site, we use to "Recipes" to refer to various resources from the docs site; but in the Docs pages, we don't use the word Recipe as far as I can tell.
Perhaps we have yet to update the docs pages to reflect a new nomenclature?  Just wanted to flag the need to synchronize these labels from website to docs site. :) 


If we need to update things in Docs, I could potentially help with that as I go through them in Gitbook; unless there's a more a more efficient way of updating them from the codebase?

**Comment by timfalls** [comment]
Copy edit suggestion: 
<img width="441" alt="Screen Shot 2022-03-01 at 4 58 17 PM" src="https://user-images.githubusercontent.com/806433/156274368-9e26787f-ea82-4538-8c73-c2c569366fb9.png">

You're a dev? We got this.
We're a protocol - not a platform. We're free, community-owned, and possess limitless opportunities for customization.

### Developers, we have you covered.
Unlock is a protocol - not a platform. It's free to use, community-owned and governed, and offers limitless customization. Build your vision, with support from friends in the Unlock community.

(iterations on this suggestion welcome from other wordsmiths :P)

**Comment by desertrat10** [comment]
Mobile Feedback: (iOS SE, on safari browser w/recently updated OS)

There should be a bit of a margin under Caroline's graphic and the "Connect with your 1000 true fans". It's stacked without space between them on mobile. 

Should we disable the "Try it Yourself" block on Mobile since you can't actually try it with mobile without some serious metamask skills and a magic wand?

**Comment by timfalls** [comment]
In the "Devs" Dropdown menu from the Main Navigation bar: 

I would suggest we make the following words clickable and link to their respective sections of docs: 

- Documentation (links to https://docs.unlock-protocol.com/unlock/)
- Integrations (links to https://docs.unlock-protocol.com/unlock/creators/plugins-and-integrations)
- Recipes (links to location in docs that we eventually label "Recipes") 


<img width="684" alt="Screen Shot 2022-03-01 at 5 10 34 PM" src="https://user-images.githubusercontent.com/806433/156275740-fb54efaa-1568-4c6d-95ef-d7f4720b5351.png">

**Comment by timfalls** [comment]
**Copy edit suggestion:**

Current: 
"Sign up for Updates
We'll send you fresh news about our platform, including new features and opportunities for the community"

Suggested: 
"Subscribe to the Unlock Newsletter:
We share updates about the protocol and celebrate our community."


<img width="410" alt="Screen Shot 2022-03-01 at 5 17 13 PM" src="https://user-images.githubusercontent.com/806433/156276221-97880397-1b54-4817-b4af-1308d2aa19ae.png">

**Comment by timfalls** [comment]
On the main page / top hero banner, I'm personally tempted to try to click on the four square dots and their headings (see screenshot).

I'm just one person and may be an exception, but thought I'd toss out the idea of making each item in the list clickable. The click could trigger an auto-scroll to a destination further down the page for more detail on that item, or link out to a more appropriate page/site (ie, docs?)

<img width="585" alt="Screen Shot 2022-03-01 at 5 08 00 PM" src="https://user-images.githubusercontent.com/806433/156279369-f41d6116-5ab3-4f84-b6d8-8725308fee02.png">

**Comment by timfalls** [comment]
Front-page copy suggestions: 

<img width="1078" alt="Screen Shot 2022-03-01 at 5 54 39 PM" src="https://user-images.githubusercontent.com/806433/156279735-2af4c4ec-cb30-4020-b736-26f12103df72.png">

///

Current copy: "Create memberships and sell access NFTs in minutes" 

Suggested update: "Create memberships and sell NFTs in minutes" (deleted "access", to avoid possible confusion around the term "access NFTs", which I don't believe is commonly understood...?)

///

We use the word "humans" in two headlines:

"For creative communities and the humans who build them."
"Connecting humans through NFT-based memberships"

Suggestion: replace one instance of "humans" with "people" to avoid redundancy. I would vote for changing "Connecting humans through..." to "Connecting people through..."

///

Current copy: 
"Your members aren't a commodity. Stop allowing platforms to treat them like one."

Suggested edit: "Your community members aren't a commodity. Unlock Protocol frees them from the platforms that treat them like one."

///

Suggestion: use **bold** instead of ALL CAPS to highlight the words "power", "revenue" and "direct"

**Comment by timfalls** [comment]
It feels like we should make the link to https://unlock-protocol.com/developers more prominent and accessible -- currently I can only find it in the footer. 

Maybe a candidate for including in the main nav "Devs" drop down menu?

**Comment by ChialiTsai** [comment]
Heading text is too close to the card.
![A641BF95-DFC7-4822-94D4-68A589D01970](https://user-images.githubusercontent.com/16527634/156300617-5c98f8c9-7864-4db4-bd45-e7d7e911ddef.jpeg)

It looks like too much space between first section and the 2nd.
![AF6EB024-F7F2-4178-9EEB-486DCA8F6EB9](https://user-images.githubusercontent.com/16527634/156300671-9af45357-9d1f-4500-9871-ae3a3736b683.jpeg)


These menu is a little too tight for the fingers on mobile.
![32C6D4C5-221B-4446-ABF6-938D355F7A67](https://user-images.githubusercontent.com/16527634/156300729-3fafbe38-53f5-4c85-b79a-4197904ffa19.jpeg)

The membership link land on a 404. 
![E29C6BF4-2F8E-4CFB-BFB4-9D048796F6DF](https://user-images.githubusercontent.com/16527634/156300796-15ef9914-51e7-4ae0-b984-8ec921a395cd.png)

**Comment by ccarfi** [comment]
| Page name | Section | Test | Mac/Safari |
| --- | --- | --- | --- |
| Home page | Header | Matches Figma | Order is incorrect. Should beDevs Creators About |
| Home page | Header | Every link in Devs section works on click | Links and copy and destinations don't match on a number of the menu items (e.g. Webflow, Shopify). Subhead of "Documentation" wasn't specified. Needs work overall. |
| Home page | Header | Creators link goes to Creators content | ok. goes to creators FAQ. |
| Home page | Header | About link goes to About page | ok |
| Home page | Header | Connect Wallet button hover and click | Does not go anywhere (should go to app?) |
| Home page | Metadata etc. | Favicon renders correctly | ok |
| Home page | Metadata etc. | og:image and twitter:image and descriptions render on Twitter and FB | renders ok. may need to update image and copy. |
| Home page | Metadata etc. | Title renders in an SEO friendly term | Currently just renders "Unlock" as title — need to update to a richer term |
| Home page | Hero | Text and bullets match Figma and render correctly | ok |
| Home page | Hero | Get Started button click | Anchor clips the header when it jumps (clips off top half of words, looks odd) |
| Home page | Hero | Connect Wallet button hover and click | Does not go anywhere (should go to app?) |
| Home page | Hero | Spotlight card matches Figma and renders correctly | Clicking on card should go to case study / blog post? |
| Home page | Animation section | Animation animates and renders correctly | Animation is jerky and doesn't have the smoothness of what Deepwork demonstrated. |
| Home page | Animation section | Text and bullets match Figma and render correctly | ok |
| Home page | Animation section | Learn More at Membership Academy button goes to (location) | need to determine where to link this to |
| Home page | How Unlock works section | Text and bullets match Figma and render correctly | ok |
| Home page | Try it yourself section | Flow takes user through and successfully grants the !unlock NFT | Do we want this to just be a CTA button with no imagery? |
| Home page | Explore active projects section | Cards and text have correct information in them | All cards show "Invalid date." |
| Home page | Explore active projects section | Clicking on every card goes to correct location | ok |
| Home page | Explore active projects section | Left and right scroll arrows work | ok |
| Home page | Dev section | Text and bullets match Figma and render correctly | ok |
| Home page | Dev section | Selector works on code section | ok |
| Home page | Dev section | Clicking button goes to docs | ok |
| Home page | Recipes section | Cards and text have correct information in them | Rightmost card clips strangely visually. Cards do not stack when screen width shrinks (perhaps should use the same scroll arrows as the "Active Projects" section above? or stack on change in viewport size?). "How to sign in with Ethereum wallet" wasn't specified. Webflow is missing. |
| Home page | Recipes section | Clicking on every card goes to correct location | ok |
| Home page | Recipes section | Explore link goes to destination | ok |
| Home page | Recipes section | Scroll button works | n/a — no scroll on live site |
| Home page | Public good section | Text and bullets match Figma and render correctly | ok |
| Home page | Public good section | Read more expands copy | n/a — no read more on live site |
| Home page | Public good section | Clicking button goes to more info | "Read on governance" CTA wasn't specified. Change CTA to "Governance FAQ" and link to https://docs.unlock-protocol.com/unlock/governance/frequently-asked-questions |
| Home page | Community section | Text and bullets match Figma and render correctly | Missing the purple dots from Figma. Header breaks across two lines on Safari, different than Figma. |
| Home page | Community section | Clicking button goes to Discord | ok |
| Home page | Footer | Email section adds email address to Hubspot | Worked great! |
| Home page | Footer | Every link in every section works on click | Memberships led to 404.Typo "Governance"Integrations 404 |

**Comment by ccarfi** [comment]
| Page name | Section | Test | Mac/Safari | iPhone 12 / OS Brave |
| --- | --- | --- | --- | --- |
| Home page | Header | Cookie banner displays | flashes then disappears? | does not display on brave, does display on ios/chrome |
| Home page | Header | Every link in Devs section works on click | Where should "Support" link go? | Where should "Support" link go? |
| Home page | Header | Creators link goes to Creators content | ok | ok |
| Home page | Header | About link goes to About page | ok | ok |
| Home page | Header | Dashboard button hover and click | ok | ok |
| Home page | Metadata etc. | Favicon renders correctly | ok | n/a |
| Home page | Metadata etc. | og:image and twitter:image and descriptions render on Twitter and FB | was not seeing twitter image when testing sharing on laptop mac/safari | ok |
| Home page | Metadata etc. | Title renders in an SEO friendly term | ok | ok |
| Home page | Hero | Get Started button click | ok | ok |
| Home page | Hero | Dashboard button hover and click | ok | ok |
| Home page | Hero | Spotlight card matches Figma and renders correctly | ok | ok |
| Home page | Animation section | Animation animates and renders correctly | animation looks low-fi | animation does not render at all on ios/brave |
| Home page | Animation section | Text and bullets match Figma and render correctly | ok | big gap between hero section and animation section on mobile. |
| Home page | Animation section | Learn more about membership button links to memberships content | ok | Should CTA button be centered? Looks like other buttons are centered in hero section. |
| Home page | How Unlock works section | Text and bullets match Figma and render correctly | ok | ok |
| Home page | Try it yourself section | Flow takes user through and successfully grants the !unlock NFT | need to test | need to test |
| Home page | Explore active projects section | Cards and text have correct information in them | ok | ok, but only shows three cards...intended? |
| Home page | Explore active projects section | Clicking on every card goes to correct location | ok | ok |
| Home page | Explore active projects section | Left and right scroll arrows work | ok | n/a |
| Home page | Explore active projects section | Explore other projects link | n/a — not in desktop | links to unlockshowcase? maybe instead not have this link and do swipe and include all projects and use same interaction design as the Recipes section below with a swipe. |
| Home page | Dev section | Text and bullets match Figma and render correctly | ok | ok |
| Home page | Dev section | Selector works on code section | ok | ok |
| Home page | Dev section | Clicking button goes to docs | ok | Should CTA button be centered? Looks like other buttons are centered in hero section. |
| Home page | Recipes section | Cards and text have correct information in them | ok | ok |
| Home page | Recipes section | Clicking on every card goes to correct location | ok | ok |
| Home page | Recipes section | Explore link goes to destination | ok | ok |
| Home page | Recipes section | Left and right scroll arrows work | ok | n/a - swipe works great |
| Home page | Public good section | Text and bullets match Figma and render correctly | update image? | ok |
| Home page | Public good section | Clicking button goes to more info | ok | ok |
| Home page | Community section | Text and bullets match Figma and render correctly | ok | ok |
| Home page | Community section | Clicking button goes to Discord | ok | ok |
| Home page | Footer | Email section adds email address to Hubspot | need to test | need to test |
| Home page | Footer | Every link in every section works on click | need to test | need to test |
| Home page | Footer banner | Footer banner link works | Membership link only works if its clicked twice???Integrations throws a 404 | Integrations throws a 404 |
| About page | Header | Cookie banner displays | ok | does not display on brave, does display on ios/chrome |
| About page | Header | Every link in Devs section works on click | need to test | ok |
| About page | Header | Creators link goes to Creators content | ok | ok |
| About page | Header | About link goes to About page | ok | ok |
| About page | Header | Dashboard button hover and click | ok | ok |
| About page | Metadata etc. | Favicon renders correctly | ok | n/a |
| About page | Metadata etc. | og:image and twitter:image and descriptions render on Twitter and FB | ok | ok |
| About page | Metadata etc. | Title renders in an SEO friendly term | Change to "About Unlock Protocol" | Change to "About Unlock Protocol" |
| About page | Page title | Renders correctly | ok | ok |
| About page | Page subtitle | Renders correctly | ok | ok |
| About page | Three boxes | Renders correctly | ok | ok |
| About page | CTA link section | Renders correctly | ok | ok |
| About page | Article feed from blog | Renders correctly | Change section subtitle to "Latest updates from Unlock" and remove rest of subtitle.Hyperlinks rendered as plain typography. Should they use the purple+underline that we see on hyperlinks in the blog article body copy itself?Article title alignment is raggedy and article titles need to be left-aligned | Change section subtitle to "Latest updates from Unlock" and remove rest of subtitle.Hyperlinks rendered as plain typography. Should they use the purple+underline that we see on hyperlinks in the blog article body copy itself? |
| About page | Footer | Email section adds email address to Hubspot |  |  |
| About page | Footer | Every link in every section works on click | ok | ok |
| About page | Footer banner | Footer banner link works | Did not render. Should it? | Did not render. Should it? |
| Blog page | Header | Cookie banner displays | ok | ok |
| Blog page | Header | Every link in Devs section works on click | ok | ok |
| Blog page | Header | Creators link goes to Creators content | ok | ok |
| Blog page | Header | About link goes to About page | ok | ok |
| Blog page | Header | Dashboard button hover and click | ok | ok |
| Blog page | Metadata etc. | Favicon renders correctly | ok | n/a |
| Blog page | Metadata etc. | og:image and twitter:image and descriptions render on Twitter and FB | ok | ok |
| Blog page | Metadata etc. | Title renders in an SEO friendly term | ok | ok |
| Blog page | RSS feed | RSS feed is discoverable on page | RSS feed discovery is missing from page | RSS feed discovery is missing from page |
| Blog page | RSS feed | RSS feed containts all correct elements (<item>, <description>, etc.) for every item in blog | unknown... | unknown... |
| Blog page | Page title | Renders correctly | ok | ok |
| Blog page | Page subtitle | Renders correctly | ok | ok |
| Blog page | List of posts | All posts are listed | Missing February product update post | Missing February product update post |
| Blog page | List of posts | Post images render | should images also be hyperlinked to the article? | should images also be hyperlinked to the article?add more space or a separator between posts. image from one post and copy from next are very close together. |
| Blog page | List of posts | Post titles render | ok | ok |
| Blog page | List of posts | Post descriptions render | ok | ok |
| Blog page | List of posts | Post dates render | Missing. Please add dates. | Missing. Please add dates. |
| Blog page | Navigation | Navigation works on first page of blog | ok | ok |
| Blog page | Navigation | Next page navigation works | ok | text stacks up and is crowded. maybe we use a different affordance for these instead of the blocks of words? |
| Blog page | Navigation | Previous page navigation works | ok | text stacks up and is crowded. |
| Blog page | Navigation | Navigation works on final page of blog | Hitting "next page" when on last page of blog navigation throws a 500 error | Hitting "next page" when on last page of blog navigation throws a 500 error |
| Blog page | Footer | Email section adds email address to Hubspot |  |  |
| Blog page | Footer | Every link in every section works on click | ok | ok |
| Blog page | Footer banner | Footer banner link works |  |  |
| Blog article page - https://unlock-protocol.com/blog/bring-your-own-nft | Header | Cookie banner displays | ok |  |
| Blog article page | Header | Every link in Devs section works on click | ok | ok |
| Blog article page | Header | Creators link goes to Creators content | ok | ok |
| Blog article page | Header | About link goes to About page | ok | ok |
| Blog article page | Header | Dashboard button hover and click | ok | ok |
| Blog article page | Metadata etc. | Favicon renders correctly | ok | n/a |
| Blog article page | Metadata etc. | og:image and twitter:image and descriptions render on Twitter and FB | share image does not render in twitter. | share image does not render in twitter. |
| Blog article page | Metadata etc. | Title renders in an SEO friendly term | ok | ok |
| Blog article page | Page title | Renders correctly | ok | ok |
| Blog article page | Page subtitle | Renders correctly | ok | ok |
| Blog article page | Post author | Post author info renders | ok | ok |
| Blog article page | Post date | Post date renders | ok | ok |
| Blog article page | Body copy | Renders correctly | Gray bullets on beige background are very low contrast and mostly unreadable. Make bullets same color as text. | Wide strings blow out the container. Was fixed on legacy site by Julien on 3/3. Also has same contract issue on bullets as desktop site. |
| Blog article page | Footer | Email section adds email address to Hubspot | need to test | need to test |
| Blog article page | Footer | Every link in every section works on click |  |  |
| Blog article page | Footer banner | Footer banner link works |  | did not render |
| Grants page | All | Need to review and update. A number of copy inconsistencies with capitalization, etc. |  |  |
| Developers page | All | Need to review and update. Direct pull from existing Developers page. |  |  |

**Comment by ccarfi** [comment]
@julien51 and @searchableguy  — ran a full set of user tests above. a few small things to tweak, but looking VERY good overall.

**Comment by searchableguy** [comment]
@ccarfi 

I think you might be looking at cached page for a few things in the test.

Integration and membership links work fine for me. 

Regarding cookie banner not showing up, if you accepted or denied cookies in the past or now - it won't show up again. You can re-check this by clearing the local storage. That's why it disappears. 

Linking to unlock-showcase is temporary - we should have our own project page. This is following the deepwork design. We cannot load all projects on the same page because there will be too many. 

RSS is available but it was renamed from blog.rss to blog.xml as we changed format to Atom. (Maybe we could keep the old path, not sure if that would be a problem given the change in format - @julien51)

Footer banner link is missing intentionally. We need to redesign this interaction.

We can fix rest of the issues.

**Comment by ccarfi** [comment]
Looking great, @searchableguy ! 

- [ ] Remove separator artifact on first page of blog
- [ ] Remove separator artifact on last page of blog

<img width="856" alt="Screen Shot 2022-03-06 at 7 16 53 AM" src="https://user-images.githubusercontent.com/214760/156929510-fd650f6a-fa5d-401b-8dc4-4ed287af6fef.png">
<img width="798" alt="Screen Shot 2022-03-06 at 7 17 02 AM" src="https://user-images.githubusercontent.com/214760/156929520-592868ba-3c5f-42fe-b2d5-4ab41a7fe28c.png">

**Comment by ccarfi** [comment]
- [ ] better headshot for littlefortunes @searchableguy 
![littlefortunes](https://user-images.githubusercontent.com/214760/156931852-55d9b29e-a824-4917-9157-095d717c0aa9.png)

**Comment by kalidiagne** [comment]
I'll share some issue I found and tips for improvemnt 

| Page name              | Section        | Report type / Description                                                                                                        | Device/browser used for test | Screen image (click for details) |
|------------------------|----------------|----------------------------------------------------------------------------------------------------------------------------------|------------------------------|--------------|
| Home page              | Header         | **Issue**: Header overlap with project title of “explore” section  on scroll on Mobile device                                    | Brave on Macbook             |   <img width="60" alt="issue-header" src="https://user-images.githubusercontent.com/20865711/157015158-91565969-21e9-4c6a-bdb7-93a5ec0b5618.png"> |
| Home page              | Footer         | **Issue**: Input for email on footer doesn't have full size, not aligned with the figma design (mobile version)                  | Brave on Macbook             |    <img width="60" alt="issue-footer" src="https://user-images.githubusercontent.com/20865711/157015340-0b63ec94-d1b1-464c-bca6-4899460650a7.png"> |
| Home page              | Explore        | **Issue**: Mouse hover on project blocks have "jump"  effect on tablet version and small screen resolutions                      | Brave on Macbook             | [issue video](https://user-images.githubusercontent.com/20865711/157015865-684f351a-f248-417a-87b2-44e2d31f2f0e.mov)  |
| Home page              | Explore        | **Tip:** Add animation on explore project blocks on mouse hover                                                                  | Brave on Macbook             | -            |
| Home page              | Intro          | **Tip:** Would be nice if the featured project on the homepage are randomised or showed with slide                               | Brave on Macbook             | -            |
| Blog                   | Blog home page | **Tip**: Add search on blog to give to user possibility to filters the post                                                      | Brave on Macbook             | -            |
| General (Website/Blog) | -              | **Tip**: Remove all gifs: are not good for the web, the file size can be very large and impact eventually on website performance | Brave on Macbook             | -            |
| General (Website/Blog) | -              | **Tip**: Missing lazy loading on images, currently missing and can improve the loading speed of the website, use video instead   | Brave on Macbook             | -            |
| General (Website/Blog) | -              | **Tip**: If possible use webp format for images                                                                                  |                              |              |

**Comment by searchableguy** [comment]
Regarding the image format, we can use Next/Image for automatic optimization but since we are not using vercel or netlify directly, we will have to optimize the image in the CI before uploading the static build.

That will increase the build time.

**Comment by ccarfi** [comment]
- [ ] Change the CTA button text from "Checkout Unlock Membership" to "Get a Free Unlock Membership" in the Home Page > Try It Yourself section

**Comment by julien51** [comment]
Re-opening to add a list of remaining items.

**Comment by timfalls** [comment]
On Published updated website, two blog posts are missing thumbnail images in post list view: 

<img width="1415" alt="Screen Shot 2022-03-08 at 10 30 09 AM" src="https://user-images.githubusercontent.com/806433/157303039-3956e2f7-2774-46b0-a107-12b085122d42.png">
