### ISSUE TITLE
Subgraph upgrade

### ISSUE THREAD

**Issue by clemsos** [unlock-protocol/unlock#8660]
Our subgraph has been stuck at spec `0.0.4` but the current version is now `0.0.6`. We need to upgrade the graph libs to the latest `0.0.26` but that takes some rewriting (see failing PR #8311).

There is a [migration guide](https://thegraph.com/docs/en/developer/assemblyscript-migration-guide/) available that may help.

Should we keep only past lock version to `0.0.4` and bump the latest to `0.0.6`?

**Comment by julien51** [comment]
> Should we keep only past lock version to 0.0.4 and bump the latest to 0.0.6?

That's a good suggestion. Let's see if any 0.0.6 lock has been "used" in the last 6 months (at least one key purchase and/or has active keys)

**Comment by julien51** [comment]
Since we keep having issues (see https://github.com/unlock-protocol/unlock/issues/8976), I think it is important that we starting thinking about moving forward.

Here is a small dump of things that I believe are important.

First we should have a single subgraph for all networks and commands to make it easy to upgrade/deploy all subgraphs at once. I  believe it will be easier to restart from scratch, rather than try to upgrade the existing subgraphs. This would also allow us to do a gradual deploy of the new "unlock subgraph v2" and slowly deprecate the existing one.

The new subgraph should gracefully handle _all_ currently supported versions of Unlock and Public Lock with a single mapping that "concats" all the events triggered in all the versions. It should then be fairly easy to add support for new versions by just adding handlers to the existing files.

# Schema

We should have a single Schema for all versions of Unlock and PublickLocks that includes the following entities:

```
Lock: 
  * address: Address
  * lockManagers: Address[]
  * keys: number[]
  * version: number
  * createdAt: number (block number)

Key:
  * lock: Lock
  * id: number
  * owner: Address
  * manager: Address
  * expiration: number
  * tokenURI: string
  * createdAt: number (block number)

LockManager:
  * address: Address
  * locks: Address[]

KeyOwner:
  * address: Address
  * keys: Key[]

```

These should be enough to get us started and we can always add more things as we go!

To build the subgraph it would be really convenient to re-use some of our tests to make sure we handle the following scenario:
* lock deployed at version
* key purchased
* key transferred
* key manager changed
* key transferred after manager changed
* key canceled by owner
* key expired by lock manager
* lock upgraded
* key purchased on upgraded lock
* key extended
* key renewed
* lock manager added
* lock manager removed

Once we have confidence that the subgraphs built locally (against hardhat?) are behaving correctly we can deploy to networks and ensure that the schemas are maintained accordingly.
