### ISSUE TITLE
Adding "upcoming events" to the website

### ISSUE THREAD

**Issue by ChialiTsai** [unlock-protocol/unlock#8662]
**Is your feature request related to a problem? Please describe.**
To help website visitors quickly join our activities and events, we should build a page to enable them to add a reminder in their calendar for any upcoming events.

**Describe the solution you'd like**
<img width="854" alt="image" src="https://user-images.githubusercontent.com/16527634/165325980-2a996e17-2ec9-45f8-9043-071e44c8567c.png">

Dependency:
a unlock-shared calender in order to use with google event api

**Comment by julien51** [comment]
@kalidiagne We have the "events" calendar publicly [there in ICS format](https://calendar.google.com/calendar/ical/c_dm3gud9ph6jqk7epq6jtij8u00%40group.calendar.google.com/public/basic.ics.

I think the best way to generate the  events pages is at "build" time (ie when we deploy the site), rather than at runtime.

**Comment by ChialiTsai** [comment]
need to add to the dropdown menu too
<img width="488" alt="image" src="https://user-images.githubusercontent.com/16527634/181259563-5a405a1d-2e33-421e-b4de-ec2d4a38f0e5.png">
