### ISSUE TITLE
store error data in redux, using constants, and generate error messages from the data

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#876]
As @cellog  [noted](https://github.com/unlock-protocol/unlock/pull/837#discussion_r243746158), we should not have JSX inside the redux store.

A better approach would be to create an errors.js (similar to constants.js) with mappings of error names to jsx and then use the string values in the redux store as well as load the jsx in the error component.

**Comment by cellog** [comment]
(continuing the conversation from #968)

So we had a misunderstanding, and I did not carefully read the title of this issue. The issue, as I tried to describe it, is twofold

1) errors should not be thrown in reducers, but instead should be recorded as error state
2) jsx should not be stored in redux state, but instead should be generated from the redux state

What this issue is describing is a third step

3) abstracting error messages into constants

In order for (3) to happen, we need a way to both store the errors in redux, and to generate the error conditions from the actual errors, so we need (1).

In order to generate the jsx for error conditions, we have to store the error condition in redux state and retrieve it. So, for (2) to happen, we need (1).

The PR I made implements (1)

In the old system, the redux store threw errors. Now that this isn't happening, there is no recording of error conditions at all. This is what (1) is about. There are 2 approaches to catching and recording errors. One is to use a middleware to listen for error conditions and dispatch "setError" actions. The other is to listen for error conditions in a meta-reducer and set the error state alongside the other state changes, this is the approach I implemented. The middleware approach has the advantage of having an action for each error in the redux dev tools log, but the disadvantage that each action triggers the entire reducer loop, degrading performance. I am open to re-implementing with that approach, it would not be a big code change.

In the course of developing this, I discovered that it was possible for multiple error conditions to exist simultaneously, so I added components to display this state and modified the redux state to allow for multiple errors. This being a first shot, I expect that the formatting and design will be drastically changed.

In addition, I found it really difficult to locate the source of an error just from the error message.  For that reason, I added additional context information, which is only displayed in development, and available in redux replay. Eventually, we may use that information in a debug dump sent from a production client if a user gets an error.

That's the reasoning behind the liberties I took in implementing the PR. If you'd like me to create new issues that more clearly describes the problem, that's totally cool.

**Comment by julien51** [comment]
> 1. errors should not be thrown in reducers, but instead should be recorded as error state
We are perfectly aligned on this and the reducers do not throw or record errors anymore as you note later. I think this is ok. I want us to focus on the 2nd issue which is the one blocking right now (always better to tackly one problem at a time!)

> 2. jsx should not be stored in redux state, but instead should be generated from the redux state.

Since the problem with our current approach is that we have JSX inside the redux store and that objects in redux needs to be "simple", I suggest using an error name, such as `E_MISSING_WALLET` inside of a JSX object as the error stored in redux and then, when rendered on page, map `E_MISSING_WALLET` to a JSX strings based on pre-defined mappings in a `errors.js`. This also presents the HUGE benefit of making it very easy to localize the app when we do because we just have to use a different `errors.js` (`errors.fr.js` for example) when we need the error to be in different language, without changing anything in the code.

So again, for now 1. is not blocking so let's not care about it (and arguably the errors which were thrown were mostly safeguards which should not happen anyway), and only focus on 2.

**Comment by cellog** [comment]
I have to disagree, please trust me on this one? I spent over 8 hours on this, starting from the premise you are speaking about, but arriving here. Can we chat later?

**Comment by cellog** [comment]
I'd like to implement this as such:

errors are defined by action creators, constants are the redux action constants. So, for example, web3Service error is defined by WEB3_ERROR, and `web3Error` function. This function accepts the original error object from web3, and stores it in error.metadata.

Then, on the UI side, I'd like to use `mapStateToProps` to generate the actual JSX for us, by using an error->jsx mapper. We can define these in `interface/helpers/ErrorMapper.js`

sound good?

**Comment by julien51** [comment]
I do not see the benefit of that approach in the context of the issue as it is now. Let's keep things simple.

**Comment by julien51** [comment]
See https://github.com/unlock-protocol/unlock/pull/985
