### ISSUE TITLE
Refactored members page

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9065]
Now that the work on the Verifiers is getting almost done, we need to work on the members page with the following elements:
* We should move the SIWE so we don't ask the user to sign and sign again
   * #9071
* #9056
* We should add the following actions:
    * #9075 
    * #9082 
    * Add a button to "mark as checked in" 
 * #9076 
 * Better UI overall: https://github.com/unlock-protocol/unlock/pull/9077 
 * Optional: ability to filter by metadata (but really that's for later as it is probably messy!)

**Comment by searchableguy** [comment]
> Ability to filter by token id, as well as key owner

> Optional: ability to filter by metadata (but really that's for later as it is probably messy!)

You can use fuse or lunr for handling search and filtering. They work well with dynamic data on the client side as long as dataset is not too big (more than a few thousand entries).

> Better UI overall as tables...

I would ditch table and use cards with a virtualized render which loads as you scroll down after x number of elements for performance. 

Because metadata can differ in shape for all members and we don't exactly control what and how the end user can use metadata. It all depends on different paywallConfig outside of our control, it would be pretty tough to build a consistent table experience without blank columns. 


Rest looks good to me.

**Comment by kalidiagne** [comment]
Closing, all task are done
