### ISSUE TITLE
EVM network support

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9304]
As of July 2022, Unlock Protocol has been deployed to:
* Mainnet
* Polygon
* Gnosis Chain
* Optimism
* BSC
* Celo
* Arbitrum
* Avalanche

We have received requests to deploy on the following as well:
* ZkSync (not supported by The Graph)
* EvMos (not supported by The Graph)
* Skale  (not supported by The Graph)
* Oasis  (not supported by The Graph)
* Cronos  (not supported by The Graph)
* Aurora

From @clemsos :
> The best way to get the Unlock protocol on your favorite chain is to go ahead and deploy the contracts.

> One main limitation to use our apps across chains is the deployment of a subgraph to index on-chain data - (see [the list of supported networks](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/)). Looks like Aurora is supported - but not EVMos :/

> Here are a "How to deploy the Protocol on a new network" section in [the README ](https://github.com/unlock-protocol/unlock/blob/master/smart-contracts/README.md#how-to-deploy-the-protocol-on-a-new-network). You can send us the addresses when the contracts are deployed and we will add them to our networks list.

If you want the protocol to be deployed on more networks, please add them as comments to this issue!

**Comment by julien51** [comment]
Related issues https://github.com/unlock-protocol/unlock/issues/7924

**Comment by thelogicaldude** [comment]
EVMOS please! This could be an awesome way to integrate with the Cosmos ecosystem!

**Comment by zheng115** [comment]
+1

**Comment by omokingsman** [comment]
EVMOS ALL THE WAY!

**Comment by carbonZEROzone** [comment]
EVMOS, please!

**Comment by Abir2021** [comment]
I am waiting to see Evmos!

**Comment by 21-Hidetaka-Ko** [comment]
I would also ask to expand to the next chain.

- Cronos
- SKALE
- Oasis

**Comment by Aaron-TheCreator** [comment]
Please add support for [Near Protocol](https://near.org/) !

**Comment by ArtAndMagic** [comment]
> 

Yes please

**Comment by russlive215** [comment]
> 

Yes please we need some intergration with aurora evm asap!

**Comment by SheenaMonique** [comment]
We're looking for some integrations compatible with aurora evm. Can anyone help us out?

**Comment by clemsos** [comment]
Hi everyone, thanks for the feedbacks ! 

The best way to get the Unlock protocol on your favourite chain is to go ahead and deploy the contracts. 

One main limitation to use our apps across chains is the deployment of a subgraph to index on-chain data - (see [the list of supported networks](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/)). Looks like Aurora is supported - but not EVMos :/

Here are the docs to [deploy the Unlock protocol on a new network](https://github.com/unlock-protocol/unlock/blob/master/smart-contracts/README.md#how-to-deploy-the-protocol-on-a-new-network).

**Comment by LivingDuality** [comment]
Hey all.  Look forward to working with everyone and Unlock in the near future.  Would love to add Skale network to the list of supported networks if at all possible.

**Comment by MaxPolarys** [comment]
Hi ! 

Would you consider adding Metis ? 

Thanks!

**Comment by TheGreatAxios** [comment]
@julien51 

Would love to see an integration with the Calypso NFT Hub, a community chain that is fully EVM compatible on the SKALE Network. It is designed to be owned by the community and to offer a variety of NFT utilities for dApps building on SKALE.

I am one of the community leaders and have had a few requests to see Unlock expand to a network where usage can be handled on-chain without any gas fees.

**Comment by sherajr** [comment]
Would love to see integration with Harmony and Findora <3

**Comment by nestorbonilla** [comment]
Hi all,

Unlock is already deployed on Celo Mainnet, but to allow developers building on Celo to experiment with the protocol without changing from chains, I would also ask for the protocol to be deployed on **Celo Alfajores** (testnet), please.

Thanks!

**Comment by julien51** [comment]
> Please add support for [Near Protocol](https://near.org/) !

Near is not EVM, so that's unlikely to happen without a significant effort from the Near community itself.

**Comment by Aeroxander** [comment]
I'd like to vouch for zkSync Era support, we are dependent on it for our Web3 Patreon named Creaton, we use Superfluid Protocol for the on-subscription and mint/burn Unlock NFTs upon the start/end of the subscription.

ZkSync is the biggest & fastest EVM-compatible chain and has a very nice UX with Native Account Abstraction so I'd would certainly be worth it to deploy on there!

**Comment by julien51** [comment]
@Aeroxander Please join our discord and tell us more about your work! This helps prioritize!

**Comment by balive** [comment]
Please add the new Pulsechain.com EVM compatible.

Network Name: PulseChain
New RPC URL: https://rpc.pulsechain.com
Chain ID: 369
Currency Symbol: PLS
Block Explorer: https://otter.pulsechain.com/
DEX: https://pulsex.com
Bridge swap from ETH to get PLS: https://bridge.pulsechain.com/
Buying PLS token (which is used for gas): https://plsburn.com
Buying PLS token on the CEX: https://www.okx.com/

I'd be happy to help provide some PLS gas, to get the contracts approved.

**Comment by PJijin** [comment]
Ronin Network (EVM Compatible)

Network Name: Ronin mainnet
New RPC URL: https://api.roninchain.com/rpc
Chain ID: 2020
Currency Symbol: RON
Block Explorer: https://app.roninchain.com/
DEX: https://katana.roninchain.com/
Bridge swap from ETH to get RON: https://bridge.roninchain.com/
Buying RON token (which is used for gas): https://purchase.roninchain.com/
Buying RON token on the CEX: https://coinmarketcap.com/currencies/ronin/markets/

**Comment by GilesLeRockeur** [comment]
> I'd like to vouch for zkSync Era support, we are dependent on it for our Web3 Patreon named Creaton, we use Superfluid Protocol for the on-subscription and mint/burn Unlock NFTs upon the start/end of the subscription.
> 
> ZkSync is the biggest & fastest EVM-compatible chain and has a very nice UX with Native Account Abstraction so I'd would certainly be worth it to deploy on there!

+1

**Comment by julien51** [comment]
@PJijin It looks like we cannot use existing EVM wallets like MetaMask on Ronin. We are not able to add support for chains that require the use of a specific wallet.

**Comment by julien51** [comment]
@Aeroxander Do you think you could help us deploy on zkSync? Can you use the checklist at the top of this issue and confirm everything exists?

**Comment by Aeroxander** [comment]
> @Aeroxander Do you think you could help us deploy on zkSync? Can you use the checklist at the top of this issue and confirm everything exists?

I'm not sure if my project will go live on zkSync, I am also looking at creating a hyperchain with zk stack or polygon cdk.

ZkSync is least EVM equivalent but still compatible mostly, Polygon zkEVM shouldn't be much of a problem I think.
ZkSync has Gnosis Safe on it now and it looks like the deployment is in hardhat only? ZkSync has a hardhat plugin so high chance it will work through there.

ZkSync has everything you need, RPC endpoint, block explorer, The Graph, so it looks like it should work like any other chain, hopefully this helps!

**Comment by julien51** [comment]
@Aeroxander Fantastic! We will look at zkSync and zkEvm then! Do you have pointers for the RPC endpoints and co?

**Comment by Aeroxander** [comment]
@julien51 https://era.zksync.io/docs/api/api.html#testnet should be enough hopefully but Alchemy also has an endpoint if you need a higher limit

**Comment by bufo24** [comment]
Core | EVM

RPC: https://1rpc.io/core
explorer: https://scan.coredao.org/

**Comment by Tguntenaar** [comment]
The _how to deploy on a new network_ docs have been moved to his [README.md](https://github.com/Tguntenaar/unlock/tree/master/governance#deploy-unlock-protocol-on-a-new-network) for those who are wondering.

**Comment by kojirohirate** [comment]
Sei

RPC: https://evm-rpc.sei-apis.com/
Explorer: https://seitrace.com/
Docs: https://www.docs.sei.io/ 

The Graph is now supporting Sei too.

**Comment by YonksTEAM** [comment]
# Expand EVM support for $EDU Chain, a forthcoming L3 Rollup Chain on the Arbitrum Orbit Stack

NOTE:  EDU chain is still in "Pre-Launch".  This feature request is to spark interest within the Unlock-Protocol community and to hopefully add EDU chain support to Unlock's Roadmap for future inclusion.

# Why $EDU Chain / Open Campus Protocol

## _Empowering educators, content creators, and students to transform learning._

![Open-Campus_banner](https://github.com/user-attachments/assets/6894df4a-7902-445c-a1a9-e2e541afcc69)

* image source: [Education Meets the Blockchain: Introducing the Open Campus Protocol](https://opencampus-xyz.medium.com/education-meets-the-blockchain-introducing-the-open-campus-protocol-c519995e9c7b) (opencampus-xyz.medium.com | 11Apr2023)

## _Over 100,000 Open Campus IDs have been claimed since launch in January, marking a significant step in adoption of its Web3 education protocol_

![Open-Campus-ID](https://github.com/user-attachments/assets/bc7fcbee-c6ef-45de-b3cf-87290d41a3bc)

* image source: [Open Campus ushers in new era of learning by empowering lifelong learners with control over their educational identity and data](https://opencampus-xyz.medium.com/open-campus-ushers-in-new-era-of-learning-by-empowering-lifelong-learners-with-control-over-their-f843cbb7c9d5) (opencampus-xyz.medium.com | 18Mar2024)

## _EDU Chain will be an L3 Rollup built on the Arbitrum Orbit Stack_

![Arbitrum_Open-Campus](https://github.com/user-attachments/assets/c4a20d21-05f7-4798-ba3b-d80abf6d135d)

* image source: [Open Campus receives grant from Arbitrum Foundation to launch EDU Chain, the first blockchain for education](https://opencampus-xyz.medium.com/open-campus-receives-grant-from-arbitrum-foundation-to-launch-edu-chain-the-first-blockchain-for-86a912cbca4f) (opencampus-xyz.medium.com | 03Jul2024)

# Why I want to see Unlock Protocol add support for $EDU Chain

- We are Pre-Launching EDUchain.Club via [EDU Chain Hackathon: Semester 1](https://dorahacks.io/hackathon/educhain/detail).  This platform will be a "Best Practices" educational and resource hub for hyper-local clubs to form and organize with minimal efforts.
- Garnering support from college aged students is a proven formula for adopting lifelong users of products & services.
- We will be building OnchainBootcamp.com, a hybrid events format, using Unlock-Protocol.  We would like to use EDU Chain for events surrounding academia.

# Additional Articles to learn more about $EDU / Open Campus

* [Decentralized Education Platform Empowers Learners With Data Ownership, Unlocking Innovative Educational Experiences](https://www.entrepreneur.com/en-au/technology/blockchain-project-empowers-learners-with-data-ownership/468014) (entrepreneur.com | 08Jan2024)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(including this article to show that Open Campus continues to release worthwhile improvements to their protocol like launching their own DID solution.)*
* [Understanding Open Campus: A Comprehensive Overview](https://messari.io/report/understanding-open-campus-a-comprehensive-overview) (messari.io | 30Nov2023)

**Comment by ogiste** [comment]
Hi, any chance there has been work to add Unlock protocol to the [Lisk ](https://lisk.com/)L2?
