### ISSUE TITLE
Saving "recipient"

### ISSUE THREAD

**Issue by julien51** [unlock-protocol/unlock#9573]
When we save the metadata on a lock with multiple purchase we save the `recipient` value which does not make much sense,.
<img width="1119" alt="Screen Shot 2022-09-07 at 7 45 27 PM" src="https://user-images.githubusercontent.com/17735/189001912-f6e0f2c0-5d4b-4bb7-9858-df6b6d81bc62.png">

**Comment by kalidiagne** [comment]
This issue is not present with the new dashboard.

I tested this scenarios to make sure the `recipient` ey is not stored anywhere.

**Scenario 1: Purchase 2 key with metadata**

https://goerli.etherscan.io/tx/0xbac6ea6f9f0e430f40fdba5bd22b686b1e741882d5237b5540ebf9f2b47d15d2

In the front-end there is no `recipient`  

<img width="752" alt="Screenshot 2022-10-12 at 10 43 52" src="https://user-images.githubusercontent.com/20865711/195295323-16a0daa2-2715-42d4-a119-189946b1a980.png">

**Scenario 2: Airdrop key without/with email**

For both of this cases, there is no `recipient` stored as visualized in the fronted 

<img width="750" alt="Screenshot 2022-10-12 at 10 45 22" src="https://user-images.githubusercontent.com/20865711/195295642-79ad947e-400e-4063-8f7a-821172659dfb.png">

Also the endpoint response contains no `recipient`

```
[
  {
    "token": "1",
    "lockName": "demo",
    "expiration": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
    "keyholderAddress": "0x8d33b257bce083ee0c7504c7635d1840b3858afd",
    "lockAddress": "0x500404480f8a7f54fa346f4ae174522639233a12",
    "email": "kld.diagne+test-email@gmail.com"
  },
  {
    "token": "2",
    "lockName": "demo",
    "expiration": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
    "keyholderAddress": "0x4ff79526ea1d492a3db2aa210d7318ff13f2012c",
    "lockAddress": "0x500404480f8a7f54fa346f4ae174522639233a12",
    "email": "kld.diagne+test-email@gmail.com"
  },
  {
    "token": "3",
    "lockName": "demo",
    "expiration": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
    "keyholderAddress": "0x80a4075391148663f04ed887e48aec65fc5ee79e",
    "lockAddress": "0x500404480f8a7f54fa346f4ae174522639233a12",
    "email": ""
  },
  {
    "token": "4",
    "lockName": "demo",
    "expiration": "115792089237316195423570985008687907853269984665640564039457584007913129639935",
    "keyholderAddress": "0xd9f3aa57576a6da995fb4b7e7272b4f16f04e681",
    "lockAddress": "0x500404480f8a7f54fa346f4ae174522639233a12",
    "email": "kld.diagne+testrecipient@gmail.com"
  }
]
```
